# Makefile for domains/sdf/atm
# Copyright (c) 1990-1996 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# @(#)makefile	1.4	3/7/96
# 
# Important!  Do not run this makefile while in
# ~ptolemy/src/domains/sdf/atm.  Instead run in from
# ~ptolemy/obj.$PTARCH/domains/sdf/atm (through the symbolic link)
# -- that way a separate directory containing, say, Sun-3 and Sun-4
# objects can be maintained.

include ../../../../mk/subdomain.mk

DIRS = kernel stars

ME = sdf/atm

