/* This file contains a table of the official C50DSP stars.  Its purpose is
 * to force the linker to retrieve the corresponding stars from their
 * library.
 *
 * DO NOT EDIT THIS FILE!  It is generated automatically from the
 * make.template file's definition of PL_SRCS.
 */

#define STR extern char *

 STR star_nm_C50FIR;
 STR star_nm_C50Allpass;
 STR star_nm_C50Biquad;
 STR star_nm_C50BiquadDSPlay;
 STR star_nm_C50DTMFPostTest;
 STR star_nm_C50Comb;
 STR star_nm_C50Goertzel;
 STR star_nm_C50GoertzelBase;
 STR star_nm_C50GoertzelPower;
 STR star_nm_C50FFTCx;
 STR star_nm_C50IIR;
 STR star_nm_C50LMS;
 STR star_nm_C50LMSGanged;
 STR star_nm_C50LMSOscDet;
 STR star_nm_C50NdftVarD;
 STR star_nm_C50RaisedCosine;
 STR star_nm_C50Sinc;
 STR star_nm_C50Window;
static char** nm_table[] = {
 &star_nm_C50FIR,
 &star_nm_C50Allpass,
 &star_nm_C50Biquad,
 &star_nm_C50BiquadDSPlay,
 &star_nm_C50DTMFPostTest,
 &star_nm_C50Comb,
 &star_nm_C50Goertzel,
 &star_nm_C50GoertzelBase,
 &star_nm_C50GoertzelPower,
 &star_nm_C50FFTCx,
 &star_nm_C50IIR,
 &star_nm_C50LMS,
 &star_nm_C50LMSGanged,
 &star_nm_C50LMSOscDet,
 &star_nm_C50NdftVarD,
 &star_nm_C50RaisedCosine,
 &star_nm_C50Sinc,
 &star_nm_C50Window,
};
