defstar {
	name { VarTime }
	domain { CG }
	desc { An abstract baseclass }
	version { $Id$ }
	author { J. T. Buck }
	copyright { 1991 The Regents of the University of California }
	location { CG demo library }
	explanation {
An abstract baseclass for stars whose execution times can be set, for use in
scheduling experiments.  You cannot create a CGVartime star, only inherit
from it.
	}
	defstate {
		name { runTime }
		type { int }
		default { 1 }
		desc { runtime for this star }
	}
	// make this a pure virtual base class
	constructor {
		noInternalState();
	}
	pure method { name { go }}
	// redefine addCode to add star full name
	method {
		name { addCode }
		type { void }
		arglist { "(const char*block,const char* name)" }
		code {
			StringList msg = "/* code generated by ";
			msg << fullName() << " */\n" << block ;
			CGStar::addCode(block);
		}
	}
	execTime {
		return int(runTime);
	}
}
