# Makefile for DE domain support
# Copyright (c) 1990 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# Programmer:  J. T. Buck
# $Id$
#
# Important!  Do not run this makefile while in ~ptolemy/src/domains/de.
# Instead run in from ~ptolemy/obj.$ARCH/domains/de (through the symbolic
# link) -- that way a separate directory containing, say, Sun-3 and Sun-4
# objects can be maintained.

include ../../../topdomain.mk

DIRS = kernel stars

ME = de

