# Makefile for sdf/dsp
# Copyright (c) 1990-1996 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# %W%	%G%
# 
# Important!  Do not run this makefile while in
# ~ptolemy/src/domains/sdf/vis.  Instead run in from
# ~ptolemy/obj.$PTARCH/domains/sdf/vis (through the symbolic link) --
# that way a separate directory containing, say, Sun-3 and Sun-4
# objects can be maintained.

include ../../../../mk/subdomain.mk

DIRS = stars

ME = sdf/vis

