.\" $Id$
.NA DTMFCodec
.SD
Dual-Tone Modulated-Frequency Coder-Decoder
.EQ
delim off
.EN
.LO "$PTOLEMY/src/domains/sdf/demo" 
.DM SDF Universe 
.SV $Id$
.AL "Brian L. Evans"
.EQ
delim $$
.EN
.LD
.IE "Goertzel algorithm"
This demo comprised of
.c DTMFGenerator
and
.c DTMFDecoder
galaxies illustrates one method for decoding touchtones using
a bank of Goertzel filters and decision logic to interpret the
output of the Goertzel filters [2].
Goertzel filters are two-pole filters that compute one DFT
coefficient [1].
From this demonstration, we have generated C implementations and
Motorola 56000 implementations by retargeting the demonstration
to the Code Generation in C (CGC) and the Motorola 56000 (CG56)
domains.
.pp
Touchtones on a telephone are generated by adding together two
single-frequency tones according to the following scheme:
.pp
      1209    1336    1477   1633
697     1       2       3      A
770     4       5       6      B
852     7       8       9      C
941     *       0       #      D
.pp
The keys A-D are not typical consumer telephones, but are available
with special switching equipment.
.pp
This demonstration represents each of these keys by an integer:
.pp
Keys 0-9:      integers 0-9
Keys A-D:      integers 10-13
Keys * and #:  integers 14 and 15
.UH REFERENCES
.ip [1]
A. V. Oppenheim and R. W. Schafer, \fIDiscrete-Time Signal Processing\fR,
Prentice-Hall: Englewood Cliffs, NJ, 1989.
.ip [2]
P. Mock, "Add DTMF generation and decoding to DSP microcomputer designes,"
\fIElectronic Data News\fR, vol. 30, pp. 205-220, March 21 1985.
.ip [3]
G. Arslan, B. L. Evans, F. A. Sakarya, and J. L. Pino,
"Performance Evaluation and Real-Time Implementation of Subspace,
Adaptive, and DFT Algorithms for Multi-Tone Detection,"
\fIProc. Int. Conf. on Telecommunications\fR,
Istanbul, Turkey, April 15-17, 1996.
.SA
lmsDTMFCodec
.ES
