.\" $Id$
.NA gaussian
.SD
Histogram and autocorrelation of a Gaussian noise source
.DE
.LO "~ptolemy/src/domains/sdf/demo"
.DM SDF Universe
.SV $Revision$ "October 20, 1990"
.AL "E. A. Lee"
.LD
This system plots a histogram and estimated autocorrelation
of samples generated by an
.c IIDGaussian
star.
Note that since the
.c Autocor
star does block processing, this demo should be run for one iteration.
The number of Gaussian samples processed will be determined
by the \fInoInputsToAvg\fR parameter of the autocorrelation block.
.Se Xhistogram
.Se "IIDGaussian"
.Se "Autocor"
.Ie "Gaussian noise"
.Ie "noise, Gaussian"
.SA
Autocor,
Xhistogram,
IIDGaussian.
.ES
