# Makefile for VHDLB domain support
# Copyright (c) 1990 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# Programmer:  Edward A. Lee
# $Id$
#
# Important!  Do not run this makefile while in ~ptolemy/src/domains/vhdlb.
# Instead run in from ~ptolemy/obj.$PTARCH/domains/vhdlb (through the symbolic
# link) -- that way a separate directory containing, say, Sun-3 and Sun-4
# objects can be maintained.

include ../../../mk/topdomain.mk

DIRS = kernel stars

ME = vhdlb
