# Test the HTML widget
#
# @Author: Christopher Hylands
#
# @Version: $Id$
#
# @Copyright (c) 1997 The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
#######################################################################

# Tycho test bed, see $TYCHO/doc/coding/testing.html for more information.

# Load up the test definitions.
if {[string compare test [info procs test]] == 1} then { 
    source [file join $TYCHO kernel test testDefs.tcl]
} {}

# Uncomment this to get a full report, or set in your Tcl shell window.
# set VERBOSE 1

# If a file contains non-graphical tests, then it should be named .tcl
# If a file contains graphical tests, then it should be called .itcl
# 
# It would be nice if the tests would work in a vanilla itkwish binary.
# Check for necessary classes and adjust the auto_path accordingly.
#
if {[namespace ptolemy {info classes File}] == {} } {
    uplevel #0 {
	set ::auto_path [linsert $auto_path 0 [file join $TYCHO kernel]] 
    }
}

######################################################################
#### HTML-1.1
# 
test HTML-1.1 {Test the HTML widget by viewing many different HTML pages} {
    # Open a HTML viewer
    set displayer [::tycho::File::openContext [file join $TYCHO doc index.html]]

    # This is the delay in ms between pages
    set delay 3000
    set time 0
    set dirs [list \
            [file join $PTOLEMY doc users_man wmwork] \
            [file join $PTOLEMY src domains sdf stars] \
            [file join $PTOLEMY public_html] \
            [file join $TYCHO doc ] \
            [file join $TYCHO kernel doc codeDoc ]]
    
    foreach dir $dirs {
        if [ file isdirectory $dir ] {
            cd $dir
            set files [glob -nocomplain *.htm *.html]
            if {$files != {}} {
                puts "@@@ Now entering $dir"
                foreach file $files {
                    if [file readable $file] {
                        incr time $delay
                        puts $file
                        after $time $displayer hyperJump [file join $dir $file]
                        update
                    }
                }
            }
        }
    }
} {}
