# Makefile for cgc/targets
# Copyright (c) 1990 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# $Id$
#
# Important!  Do not run this makefile while in ~ptolemy/src/domains/cg.
# Instead run in from ~ptolemy/obj.$PTARCH/domains/cg (through the symbolic
# link) -- that way a separate directory containing, say, Sun-3 and Sun-4
# objects can be maintained.

include ../../../../mk/subdomain.mk

DIRS = main cm5

ME = cgc/targets

