#! /bin/sh
# usage: pigiRpcConsole <vem-rpc-args>
# Version: $Id$
#
# This is typically invoked from wtih pigiRpcShell as the $COMMAND.
# It brings up an xterm with pigiRpc running inside.

xterm -display $DISPLAY -title "pigiRpc console" -bg darkgreen -fg yellow \
	-e $PIGIRPC $* &
