#! /bin/sh
# $Id$
# script for starting the pigiRpc process for user shells other than csh/tcsh
#
# Copyright (c) 1992 The Regents of the University of California.
#			All rights reserved.
# Programmer: J. Buck
#
# This script is designed for use by folks who use a shell other than
# csh, where that shell has nothing analogous to .cshrc to set up the
# environment.  It sets up the environment correctly for pigiRpc.  To use
# it, make this script executable, set the PIGIRPC environment variable
# to the full path of this script, and type "pigi".

# Define this variable to point to the root of the Ptolemy directory.
# You may need to change it for your system.
PTOLEMY=/usr/users/ptolemy

# Set PTARCH properly.  SunOS has this
test -x /bin/arch && PTARCH=`/bin/arch`
# Ultrix has this
test -x /bin/machine && PTARCH=`/bin/machine`

# If PTARCH still is not set you need to do something else!
export PTARCH

# Add the Ptolemy directories to the PATH.  You may also need to add
# other directories if pigi fails to find any programs, or if some
# of your private stars want to invoke special programs that need to
# be on the path.

PATH=$PTOLEMY/bin:$PTOLEMY/bin.${PTARCH}:$PATH
export PATH

# Now exec the real pigiRpc.

exec pigiRpc $*
