#########################################################################
# @Version: @(#)IconOval.itcl	1.18 07/29/98
# @Author: H. John Reekie
#
# @Copyright (c) 1996-1998 The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
##########################################################################


########################################################################
## IconOval
#
# <i>IconOval</i> is an Oval with connecting terminals on it, intended
# for use as an icon in block diagrams and the like. It has just two
# coordinates, which are the _x_ and _y_ coordinates of its center.
# 
# <p><b>Options</b>:
# 
# _IconOval_ has all options of <a href="IconItem.html">IconItem</a>
# and <a href="LabeledOval.html">LabeledOval</a>. In addition, each
# terminal is a component.  The <b>-fill</b> option, however, defaults
# to white instead of null, and the <b>-hsize</b> and <b>-vsize</b>
# options both default to 50.
#
# </ul>
# 
# <p><b>Components</b>
#
# _IconOval_ has all components of <a href="IconItem.html">IconItem</a>
# and <a href="LabeledOval">LabeledOval</a>.
# 
# <p><b>Bugs</b>: If the input and output terminals are not positioned
# at the compass points then the terminal doesn't connect to the oval.
# 
# <p><b>Example</b>: Create an icon:
# <tcl quiet><pre>
#   package require slate.demo
#   set slate [::demo::newslate "An IconOval example"]
#   set icon [$slate create IconOval 80 80 &#92
#       -fill green &#92
#       -graphics {line 20 50 80 50 -width 4
#                  line 50 20 50 80 -width 4} &#92
#       -tags moveable]
#   $slate call $icon terminal input Terminal 0 50 &#92
#       -direction w &#92
#       -style circle &#92
#       -fill red
#   $slate call $icon terminal output Terminal 100 50 &#92
#       -style doublearrowout  &#92
#       -fill blue
# </pre></tcl>
# 
# <p><b>Enhancements</b>: Make terminals connect anywhere on the oval.
#
# <p><b>Links</b>
# 
# <ul>
# <li><a href="../internals/howtoread.html">Reading <i>ComplexItem</i>
# documentation</a>.
# <li><a href="../internals/items.html">Complex item classes</a>.
# </ul>
#
class ::tycho::IconOval {
    inherit ::tycho::IconItem

    ###################################################################
    ####                         public procs                      ####

    # Create a new item
    proc construct {id canvas slate tags x y args}

    ###################################################################
    ####                         private variables                 ####

    # All methods are looked up through a table
    private common methodtable

    # All options have a default value
    private common optiondefault
}


###################################################################
####                       class initialization                ####

catch {::tycho::LabeledOval}
namespace eval ::tycho::IconOval {
    #### Set method table
    array set methodtable [array get ::tycho::LabeledOval::methodtable]
    array set methodtable [array get ::tycho::IconItem::methodtable]
 
    set methodtable(_coords)     ::tycho::LabeledOval::coords
    set methodtable(construct)   ::tycho::IconOval::construct

    #### Set option defaults
    array set optiondefault [array get ::tycho::LabeledOval::optiondefault]
    array set optiondefault [array get ::tycho::IconItem::optiondefault]
 
    # Make it round and white
    set optiondefault(-hsize) 50
    set optiondefault(-vsize) 50
    set optiondefault(-fill)  white
}


#########################################################################
#### construct
#
body ::tycho::IconOval::construct {id canvas slate tags x y args} {
    # Initialize the options
    foreach {opt val} [concat [array get optiondefault] $args] {
	set option([string trimleft $opt -]$id) $val
    }
    set anchor $option(anchor$id)
    set option(anchor$id) nw
 
    # Create the oval.
    eval [list ::tycho::LabeledOval::_construct $id $canvas $slate $tags] \
            $x $y [expr $x + $option(hsize$id)] [expr $y + $option(vsize$id)]

    # Adjust anchor
    _anchor $id $canvas $slate $anchor
}
