##########################################################################
# @Version: $Id$
# @Author: H. John Reekie
#
# @Copyright (c) 1996-%Q% The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
##########################################################################


#######################################################################
#### Point
#
# The shape of items with a single pair of coordinates. Items with
# this shape include <I>text</I>, <I>bitmap</I>, <I>image</I>,
# and <I>Axis</I>..
#
#  <P><b>Primitive aspects</b>
#
# <ul>
# <li><B>origin</B>: The coordinates of the item.
# </ul>
#
# <p><b>Derived aspects</b>
#
# <P>None.
#
# <p><b>Bugs</b>: (none) 
#
# <p><b>Enhancements</b>: (none)
#
# <p><b>Links</b>
# 
# <ul>
# <li><a href="../internals/shapes.html">An overview of Shape classes</a>
# <li><a href="../internals/index.html">Infrastructure contents</a>
# <li><a href="../codeDoc/index.html">Class documentation index</a>
# </ul>
#

#
class ::tycho::Point {
    inherit ::tycho::Shape

    ###################################################################
    ####                         public procs                      ####

    # Get one or more aspects of an item
    proc _aspect {id canvas slate args}

    # Attach a set of grapples to an item
    proc _grapple {id canvas slate interactor args}

    # Generate an error, since point objects cannot be reshaped
    proc _reshape {id canvas slate x y args}

    # Generate an error, since point objects cannot be reshaped
    proc _reshapeclick {id canvas slate x y args}

    # Generate an error, since point objects cannot be reshaped
    proc _reshapedrag {id canvas slate x y}

    # Generate an error, since point objects cannot be reshaped
    proc _reshaperelease {id canvas slate x y}
}


#######################################################################
#### _aspect
#
# Return the value of an aspect. The only valid aspect is "origin."
#
body ::tycho::Point::_aspect {id canvas slate args} {
    set coords [$slate coords $id]
    set result {}

    if { $args == "" } {
    	return [list "origin"]
    } else {
	foreach aspect $args {
	    switch -exact $aspect {
		"origin" {
		    eval lappend result $coords
		}
		default {
		    error "Invalid aspect \"$aspect\" of line shape"
		}
	    }
	}
    }
    return $result
}

#######################################################################
#### _reshape
#
body ::tycho::Point::_reshape {id canvas slate x y args} {
    error "Point objects cannot be reshaped"
}

#######################################################################
#### _reshapeclick
#
body ::tycho::Point::_reshapeclick {id canvas slate x y args} {
    error "Point objects cannot be reshaped"
}

#######################################################################
#### _reshapedrag
#
body ::tycho::Point::_reshapedrag {id canvas slate x y} {
    error "Point objects cannot be reshaped"
}

#######################################################################
#### _reshaperelease
#
body ::tycho::Point::_reshaperelease {id canvas slate x y} {
    error "Point objects cannot be reshaped"
}
