##########################################################################
# @Version: $Id$
# @Author: H. John Reekie
#
# @Copyright (c)	1996 The Regents of the University of California.
# All rights reserved.
# 
# Permission is	hereby granted,	without	written	agreement and without
# license or royalty fees, to use, copy, modify, and distribute	this
# software and its documentation for any purpose, provided that	the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO	EVENT SHALL THE	UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT,	SPECIAL, INCIDENTAL, OR	CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN	ADVISED	OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES	OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.	THE SOFTWARE
# PROVIDED HEREUNDER IS	ON AN "AS IS" BASIS, AND THE UNIVERSITY	OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT,	UPDATES,
# ENHANCEMENTS,	OR MODIFICATIONS.
#							  COPYRIGHTENDKEY
##########################################################################


# Explicitly load the superclass. I don't really know why this is
# needed, but the common arrays get upset otherwise.
namespace ::tycho {
    if { [::info classes Picture] == "" } {
	uplevel #0 {source $tychoslate/Picture.itcl}
    }
}

##########################################################################
## Solid
#
# A psuedo-3D polygon. This accepts all "standard" relief options: flat,
# raised, sunken, ridge, and groove. Because
# of some funnies with Tk's coordinates, the last two don't work too
# well with sharp angles (< 25 or so), but with moderate angles
# they look fine.
#
# <a href="../internals/howtoread>Reading <i>Picture</i> documentation</a>.
#
class ::tycho::Solid {
    inherit ::tycho::Picture

    # Create a new item
    proc construct {id canvas slate tags args}

    ###################################################################
    ####                            options                        ####

    # The width of the relief border
    common _borderwidth

    # The color of the frame
    common _color

    # The relief: raised, sunken, groove, ridge, or flat
    common _relief

    ###################################################################
    ####                     option update procs                   ####

    # Update the *-borderwidth* option
    proc _borderwidth {id canvas slate borderwidth}
    
    # Update the *-color* option
    proc _color {id canvas slate color}
    
    # Update the *-relief* option
    proc _relief {id canvas slate relief}

    ###################################################################
    ####                         public procs                      ####

    # Set or get the item's coordinates
    proc coords {id canvas slate args}

    # Create a ghost of the polygon
    proc ghost {id canvas slate}

    ###################################################################
    ####                         picture components                ####

    # The polygons that are "lit"
    common lit
    
    # The polygons in the inside shadow (ridge and groove reliefs only)
    common notlit
    
    # The polygons that are "shaded"
    common shaded
    
    # The polygons in the inside lit region (ridge and groove reliefs only)   
    common notshaded
    
    # The polygonal surface
    common surface

    ###################################################################
    ####                         protected variables               ####

    # The object used to get shades of color
    common colorShadesObject

    # All methods are looked up through a table
    common methodtable

    # All options have a default value
    common optiondefault

    # The "shape" of items of this class
    common shape "polygon"

    ###################################################################
    ####                        private procs                      ####

    # Adjust the border polygons to new coordinates
    private proc adjust {id canvas name shade coords} {}

    ###################################################################
    ####                       class initialization                ####

    #### Set method table
    array set methodtable [array get ::tycho::Picture::methodtable]

    set methodtable(_borderwidth) ::tycho::Solid::_borderwidth
    set methodtable(_color)       ::tycho::Solid::_color
    set methodtable(_relief)      ::tycho::Solid::_relief

    set methodtable(construct)   ::tycho::Solid::construct
    set methodtable(coords)      ::tycho::Solid::coords
    set methodtable(ghost)       ::tycho::Solid::ghost

    #### Set option defaults
    array set optiondefault [array get ::tycho::Picture::optiondefault]

    set optiondefault(-color)       background
    set optiondefault(-borderwidth) 2
    set optiondefault(-relief)      raised
}

##########################################################################
## -borderwidth option configuration
#
# Update the *-borderwidth* configuration option. Just cause a redraw
# by calling the coords{} method with the current coordinates.
#
# This could be made a lot faster by duplicating code.
#
body ::tycho::Solid::_borderwidth {id canvas slate borderwidth} {
    set _borderwidth($id) $borderwidth
    eval coords [$canvas coords $primary($id)]
}

##########################################################################
## -color option configuration
#
# Update the *-color* configuration option.
#
body ::tycho::Solid::_color {id canvas slate color} {
    set _color($id) $color
    set colorShadesObject($id) [::tycho::Shades::new $_color($id)]

    # FIXME: quick and dirty
    _relief $id $canvas $_relief($id)
    $canvas itemconfigure $surface($id) -fill [$colorShadesObject($id) matt]
}

##########################################################################
## -relief option configuration
#
body ::tycho::Solid::_relief {id canvas slate relief} {
    set _relief($id) $relief
    if { $_relief($id) == "ridge" || $_relief($id) == "groove" } {

	set light [$colorShadesObject($id) light]
	set dark  [$colorShadesObject($id) dark]

	if { $_relief($id) == "groove" } {
	    set light $dark
	    set dark [$colorShadesObject($id) light]
	}

	# Change the color of the lit and shaded components
	foreach i $lit($id) {
	    $canvas itemconfigure $i -fill $light
	}
	foreach i $shaded($id) {
	    $canvas itemconfigure $i -fill $dark
	}

	# If the relief has changed to ridge or groove, then we
	# have to create the inside border polygons, and move
	# the surface if it exists.
	if { ! [info exists notlit($id)] } {

	    set coords [$canvas coords $primary($id)]

	    assign inside junk1 junk2 \
		    [polyBorders 45 -135 $coords $_borderwidth($id)]
	    assign inside notlitC notshadedC \
		    [polyBorders 45 -135 $inside $_borderwidth($id)]

	    set notlit($id)    {}
	    set notshaded($id) {}

	    adjust $id $canvas "notshaded" $light $notshadedC
	    adjust $id $canvas "notlit"    $dark  $notlitC

	    if { [::info exists surface($id)] } {
		eval $canvas coords $surface($id) $inside
	    }
	} else {
	    foreach i $notshaded($id) {
		$canvas itemconfigure $i -fill $light
	    }
	    foreach i $notlit($id) {
		$canvas itemconfigure $i -fill $dark
	    }
	}
    } else {
	set light [$colorShadesObject($id) light]
	set dark  [$colorShadesObject($id) dark]

	if { $_relief($id) == "sunken" } {
	    set light $dark
	    set dark [$colorShadesObject($id) light]
	} elseif { $_relief($id) == "flat" } {
	    set light [$colorShadesObject($id) matt]
	    set dark $light
	}

	# Change the color of the various components
	foreach i $lit($id) {
	    $canvas itemconfigure $i -fill $light
	}
	foreach i $shaded($id) {
	    $canvas itemconfigure $i -fill $dark
	}

	# If the relief has changed _from_ ridge or groove, then we
	# delete the inside border polygons and move the surface.
	if { [::info exists notlit($id)] } {
	    
	    eval $canvas delete $notlit($id) $notshaded($id)
	    unset notlit($id)
	    unset notshaded($id)

	    if { [::info exists surface($id)] } {
		set coords [$canvas coords $primary($id)]
		assign inside junk1 junk2 \
			[polyBorders 45 -135 $coords $_borderwidth($id)]
		eval $canvas coords $surface($id) $inside
	    }
	}
    }
}

##########################################################################
## adjust name shade coords
#
# Adjust a list of polygons to a new set of coordinates
#
body ::tycho::Solid::adjust {id canvas name shade coords} {

    # Move the components to their new locations.
    set polys [set [set name]($id)]
    set count [min [llength $polys] [llength $coords]]
    set usepolys  [ltake $polys $count]
    set usecoords [ltake $coords $count]
    foreach p $usepolys c $usecoords {
	eval $canvas coords $p $c
    }

    # If there weren't enough polygons, create some more. Lower the
    # new components to the same level as the primary component.
    if { [llength $coords] > $count } {
	set tags [$canvas gettags $id]
	set moreneeded [ldrop $coords $count]
	foreach c $moreneeded {
	    set p [eval $canvas create polygon $c \
		    -fill $shade \
		    -tags [list $tags]]
	    lappend [set name]($id) $p
	    $canvas lower $p $primary($id)
	}
    } elseif { [llength $coords] < $count } {
	# If there were too many polygons, delete the leftovers
	set leftovers [ldrop $polys $count]
	set [set name]($id) [ltake $polys $count]
	# FIXME: replace with eval $canvas delete $leftovers and TEST
	foreach p $leftovers {
	    $canvas delete $p
	}
    }
}

##########################################################################
## construct
#
body ::tycho::Solid::construct {id canvas slate tags args} {
    getalloptions options args

    # Initialize the options
    foreach {option value} [concat [array get optiondefault] $options] {
	set _[string trimleft $option -]($id) $value
    }

    # This object is used to get the shades of color
    set colorShadesObject($id) [::tycho::Shades::new $_color($id)]
    
    # Create the primary component for the outline coordinates
    set primary($id) [eval $canvas create polygon $args \
	    [list -tags $tags -fill ""]]

    # Create the surface component with null size
    set surface($id) [$canvas create polygon 0 0 0 0 0 0 \
	    -fill [$colorShadesObject($id) matt] -tags $tags]

    # Create the borders using the coords{} method. Set the list and
    # shaded components to null to save work in coords{}.
    set lit($id)    {}
    set shaded($id) {}

    eval coords $id $canvas $slate $args
}


    ##################################################################
    ##################################################################
    ####                     public methods                       ####

##########################################################################
## coords
## coords {coord}+
#
# Query or set the coordinates of the object. This procedure ensures
# that the last two points are the same as the first two.
#
body ::tycho::Solid::coords {id canvas slate args} {
    # No args: just return coordinates
    if { $args == "" } {
	set coords [$canvas coords $primary($id)]
	return $coords
    }

    # Make sure that end point is same as start point
    if { [lindex $args 0] != [lindex $args [expr [llength $args] - 2]] \
	    || [lindex $args 1] != [lindex $args end] } {
	lappend args [lindex $args 0]
	lappend args [lindex $args 1]
    }

    # Move the primary.
    set coords $args
    eval $canvas coords $primary($id) $coords

    # Get the coordinates of the borders and the surface component
    assign inside litC shadedC \
	    [polyBorders 45 -135 $coords $_borderwidth($id)]

    # Adjust the positions of the border polygons, creating and
    # deleting them as necessary.
    adjust $id $canvas "lit"    [$colorShadesObject($id) light] $litC
    adjust $id $canvas "shaded" [$colorShadesObject($id) dark]  $shadedC

    # If the relief is "groove" or "ridge," adjust the inner borders
    # as well. Note that _inside_ is over-written with new values.
    if { $_relief($id) == "ridge" || $_relief($id) == "groove" } {
	assign inside notlitC notshadedC \
		[polyBorders 45 -135 $inside $_borderwidth($id)]

	adjust $id $canvas "notshaded" [$colorShadesObject($id) light] $notshadedC
	adjust $id $canvas "notlit"    [$colorShadesObject($id) dark]  $notlitC
    }

    # Change the co-ordinates of the surface component, if it exists.
    if { [::info exists surface($id)] } {
	eval $canvas coords $surface($id) $inside
    }
}

##########################################################################
## ghost
#
# Create and return a "ghost" of the item.
#
# FIXME: Why do we need to provide this -- the Slate should do the
# right thing from the shape variable?
#
body ::tycho::Solid::ghost {id canvas slate} {
    eval $canvas create polygon [$canvas coords $primary($id)] \
	    -outline grey {-fill {}}
}

##########################################################################
## transform mode args
#
# Transformation on a solid has to be overridden to make sure that
# the "direction" in which the coordinates run remains correct.
# Without this overriding, the solid will change relief from
# "raised" to "sunken," or vice versa.
#
#body ::tycho::Solid::transform {mode args} {
#    if { $mode == "flip" || $mode == "flop" } {
#	eval $this coords [lineReverse [$this coords]]
#    }
#    eval [$this shape] transform $mode $args
#}
