#! /bin/sh
# usage: pigiRpcDebug <vem-args>
# Version: $Id$
#
# This is typically invoked from wtih pigiRpcShell as the $COMMAND.
# It brings up the debugger running PIGIRPC.

dbgcmdfile=/tmp/rpc$$
cat > $dbgcmdfile <<EOF
break main
run $*
EOF

DEBUG='xterm -title pigiRpc_debug_window -bg black -fg green -e gdb'

${PT_DEBUG-$DEBUG} -command=$dbgcmdfile $PIGIRPC &
