# Test suite for testPath that will work from within itclsh
#
# @Author: Christopher Hylands
#
# @Version: $Id$
#
# @Copyright (c) 1996 The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
#######################################################################

if {[string compare test [info procs test]] == 1} then { 
    source testDefs.tcl
} {}
source [file join .. Path.tcl]


test Path-1.1 { Check out files in the current dir vs. paths with env vars} {
    set localfile [::tycho::expandPath foo]
    set envfile [::tycho::expandPath \
	    [file join \$TYCHO kernel test foo]]

    # Verify that expanding a local file results in part
    # of the directory being tycho/kernel/test
    set localfilecheck [string range $localfile \
	    [ expr {[string length $localfile] - \
	    [string length [file join tycho kernel test foo]]}] end]

    set envfilecheck [string range $envfile \
	    [ expr {[string length $envfile] - \
	    [string length [file join tycho kernel test foo]]}] end]
    
    list $localfile $envfile $localfilecheck $envfilecheck
} {/export/watson/watson3/cxh/pt/tycho/kernel/test/foo /export/watson/watson3/cxh/pt/tycho/kernel/test/foo tycho/kernel/test/foo tycho/kernel/test/foo}

test Path-1.2 { tilde expand a user that does not exist} {
    catch {::tycho::expandPath ~anonexistantUser} errMsg
    list $errMsg
} {{user "anonexistantUser" doesn't exist}}

test Path-1.3 { tilde expand a user that does exist (Unix only)} {
    global tcl_platform
    if { $tcl_platform(platform) == "unix" } {
	set rootHome [::tycho::expandPath ~root/etc/passwd]
    } else {
	# If we are not running under Unix, then just return the right value.
	set rootHome /etc/passwd
    }
    list $rootHome
} {/etc/passwd}

doneTests
