# Yes-no query box.
#
# @Authors: Wan-Teh Chang, Joel King, and Edward A. Lee
#
# @Version: @(#)YesNoQuery.itcl	1.18   12/05/97
#
# @Copyright (c) 1995-1998 The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
##########################################################################


##########################################################################
#### askuser
# Ask the user a question, and return 0 or 1 for answers No and Yes.
# Also return 0 if the user dismisses the query window without responding.
# This is done by opening a modal dialog box ("modal" means that nothing
# further happens in this thread of control until this dialog box is
# dismissed).
# <p>
# This procedure indirectly calls <code>update</code>, a Tk utility
# that processes pending events, including mouse events. If this
# procedure is called from within an Itcl object, directly or
# indirectly, it may be necessary to take precautions to prevent the
# calling object from being deleted during the call. Because of a
# defect in at least some versions of Itcl, failure to do so can result
# in catastrophic failure of the application (a core dump). In Tycho
# objects, the <code>safeEval</code> method should be used to evaluate
# this procedure or any method or procedure that in turn calls this
# procedure. If the procedure is called from the top level or from a
# Tcl procedure that is not itself called from within an Itcl object,
# then there is no cause for worry.
#
proc ::tycho::askuser {question} {
    set name [autoName .yesno]
    uplevel #0 [list ::tycho::YesNoQuery $name -text $question]
    set response [::tycho::Dialog::wait $name]
    if {$response == 1} {
        return 1
    } else {
        return 0
    }
}

##########################################################################
#### YesNoQuery
# Query the user for a yes/no response to a question. The command to
# execute in response to the user's answer can be specified using the
# options "-yescommand" and "-nocommand". The value returned by whichever
# command is executed can be obtained by creating the dialog box using
# the procedure <code>wait</code> after creating the instance.
# This functionality can be accessed more simply through the procedure
# <code>::tycho::askuser</code>.
#
class ::tycho::YesNoQuery {
    inherit ::tycho::Dialog

    # Specify the command to execute on a yes response.
    itk_option define -yescommand yescommand YesCommand \
	    "::tycho::Dialog::answer 1"

    # Specify the command to execute on a no response
    itk_option define -nocommand nocommand NoCommand \
	    "::tycho::Dialog::answer 0"

    constructor {args} {}
}

##########################################################################
#### constructor
#
body ::tycho::YesNoQuery::constructor {args} {

    configure -bitmap question

    #
    # Pack the yes and no buttons.
    #
    addButton yes -text "Yes" \
            -underline 0 \
	    -command "$this execCommand -yescommand; \
	    $this prevWindow; \
	    delete object $this"
    addButton no -text "No" \
            -underline 0 \
	    -command "$this execCommand -nocommand; \
	    $this prevWindow; \
	    delete object $this"
    default yes

    # bind $prefix <Return> "$this invoke yes"

    #
    # Explicitly handle configs that may have been ignored earlier.
    #
    eval itk_initialize $args
}
