#!/bin/csh -fx
# 
# Version: $Id$

lpr -P$PRINTER users_manIX.ps
lpr -P$PRINTER references.ps
lpr -P$PRINTER ptglossary.ps
lpr -P$PRINTER sharedlib.ps
lpr -P$PRINTER filter.ps
lpr -P$PRINTER x.ps
lpr -P$PRINTER install.ps
lpr -P$PRINTER xgraph.ps
lpr -P$PRINTER vem.ps
lpr -P$PRINTER documents.ps
lpr -P$PRINTER vhdl.ps
lpr -P$PRINTER c50.ps
lpr -P$PRINTER cg56.ps
lpr -P$PRINTER cgc.ps
lpr -P$PRINTER cg.ps
lpr -P$PRINTER de.ps
lpr -P$PRINTER fsm.ps
lpr -P$PRINTER sr.ps
lpr -P$PRINTER pn.ps
lpr -P$PRINTER bdf.ps
lpr -P$PRINTER ddf.ps
lpr -P$PRINTER hof.ps
lpr -P$PRINTER sdf.ps
lpr -P$PRINTER domains.ps
lpr -P$PRINTER ptcl.ps
lpr -P$PRINTER pigi.ps
lpr -P$PRINTER overview.ps
lpr -P$PRINTER users_manTOC.ps
lpr -P$PRINTER title.ps
