# Makefile for domains/cg56
# Copyright (c) 1990-1997 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# @(#)makefile	1.5	04/07/97
#
# Important!  Do not run this makefile while in ~ptolemy/src/domains/cg.
# Instead run in from ~ptolemy/obj.$PTARCH/domains/cg (through the symbolic
# link) -- that way a separate directory containing, say, Sun-3 and Sun-4
# objects can be maintained.

include ../../../../mk/subdomain.mk

DIRS = stars

ME = cg56/dsp

