# Makefile for domains/de/sip
# Copyright (c) 1997-%Q% The Regents of the University of California.
#                       All Rights Reserved.
#		       
# $Id$
#
# Important!  Do not run this makefile while in ~ptolemy/src/domains/de/sip.
# Instead run in from ~ptolemy/obj.$PTARCH/domains/de/sip (through the symbolic
# link) -- that way a separate directory containing, say, Solaris and HP
# objects can be maintained.

include ../../../../mk/subdomain.mk

DIRS = kernel ptsip

ME = de/sip
