# Makefile for cgc/tcltk
# Copyright (c) 1990 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# $Id$
#
# Important!  Do not run this makefile while in ~ptolemy/src/domains/cgc.
# Instead run in from ~ptolemy/obj.$ARCH/domains/cgc (through the symbolic
# link) -- that way a separate directory containing, say, Sun-3 and Sun-4
# objects can be maintained.

include ../../../../subdomain.mk

DIRS = stars targets

ME = cgc/tcltk

