#! /bin/sh
#
# Version id: $Id$
# Programmer: E. A. Lee,
# inspired by previous programs by David A. Wheeler and HorngDar Lin
#
# nr2mml - convert a ptolemy troff documentation file into a mml file.
#
# The PTOLEMY environment variable must be set to point to the home
# directory of the Ptolemy installation.
#
# Usage:
#         Cat sect.* files to xxxx.mm.
#         Run nr2mml xxxx.mm.
#         Create a new maker file
#		(e.g. using $PTOLEMY/doc/users_man/pigi.doc)
#         Import xxxx.mml.
#
# Copyright (c) 1993 The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#                                                        COPYRIGHTENDKEY
#

if [ ! $?PTOLEMY ] 
 then
  PTOLEMY=~ptolemy
fi

if [ ! -f $1 ]
 then
  echo "Sorry, cannot find file $1" 1>&2
  exit 1
fi

if [ ! -r $1 ]
 then
  echo "Sorry, cannot read file $1" 1>&2
  exit 2
fi

# Actual translation follows.

FRAMEBIN=$PTOLEMY/doc/fmconvert

soelim $* | \
   sed -f $FRAMEBIN/nr2mml.sed | \
   awk -f $FRAMEBIN/nr2mml.awk > ${1}.mml

