# Ptolemy program Makefile for wfir
# Version Identification:
# $Id$
# Copyright (c) 1990-1994 The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY 
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES 
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF 
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF 
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#

VPATH         = ../../../src/filters/wfir

PROGRAM	      = wfir

OBJS	      = wfir.o

SRCS	      = wfir.f

HDRS	      =

EXTHDRS	      =

DEST	      = ../../../bin.$(ARCH)

FFLAGS	      = -O

# This will probably only work on suns
LDFLAGS	      = -Bstatic

LIBS	      = /usr/lib/libm.a

FC	      = f77

LINKER	      = $(FC)

MAKEFILE      = Makefile

PRINT	      = pr

all:		$(PROGRAM)

$(PROGRAM):     $(OBJS) $(LIBS)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

clean:;		rm -f $(OBJS) make.out makelint.out gmon.out core $(PROGRAM)

depend:;	@mkmf -f $(MAKEFILE) PROGRAM=$(PROGRAM) DEST=$(DEST)

install:	$(PROGRAM)
		mv -f $(PROGRAM) $(DEST)/$(PROGRAM)

check:;		sccs check; sccs prt -y *.f > /dev/null

print:;		$(PRINT) $(HDRS) $(SRCS)

program:        $(PROGRAM)

sources:	$(SRCS)

tags:           $(HDRS) $(SRCS); @ctags $(HDRS) $(SRCS)

update:		$(DEST)/$(PROGRAM)
###
