/* This file contains a table of the official SRCGC stars.  Its purpose is
 * to force the linker to retrieve the corresponding stars from their
 * library.
 *
 * DO NOT EDIT THIS FILE!  It is generated automatically from the
 * make.template file's definition of PL_SRCS.
 */

#define STR extern char *

 STR star_nm_SRCGCAdd;
 STR star_nm_SRCGCAnd;
 STR star_nm_SRCGCConst;
 STR star_nm_SRCGCIntToString;
 STR star_nm_SRCGCMux;
 STR star_nm_SRCGCPre;
 STR star_nm_SRCGCPrinter;
 STR star_nm_SRCGCScanner;
 STR star_nm_SRCGCStringToInt;
 STR star_nm_SRCGCSub;
 STR star_nm_SRCGCWhen;
static char** nm_table[] = {
 &star_nm_SRCGCAdd,
 &star_nm_SRCGCAnd,
 &star_nm_SRCGCConst,
 &star_nm_SRCGCIntToString,
 &star_nm_SRCGCMux,
 &star_nm_SRCGCPre,
 &star_nm_SRCGCPrinter,
 &star_nm_SRCGCScanner,
 &star_nm_SRCGCStringToInt,
 &star_nm_SRCGCSub,
 &star_nm_SRCGCWhen,
};
