# Test suite for Stack that will work from within itclsh
#
# @Author: Christopher Hylands
#
# @Version: $Id$
#
# @Copyright (c) 1996-%Q% The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
#######################################################################

if {[string compare test [info procs test]] == 1} then { 
    source [file join $TYCHO kernel test testDefs.tcl]
} {}

# If necessary load up the class definitions
if {[namespace tycho {info classes Stack}] == {} } {
    namespace tycho
    source [file join $TYCHO kernel Stack.itcl]
}

test Stack-1.1 {Build a Stack} {
    catch {delete object foo}
    ::tycho::Stack foo
    foo clear
    set getnothing [foo pop]
    foo push a
    foo push b
    set getb [foo pop]
    set geta [foo pop]
    list $getnothing $getb $geta
} {{} b a}


test Stack-1.3 {Build a Stack, push {} onto it twice} {
    catch {delete object foo}
    ::tycho::Stack foo
    set getnothing [foo pop]
    foo push {}
    foo push {}
    set getb [foo pop]
    set geta [foo pop]
    list $getnothing $getb $geta
} {{} {} {}}
