#! /bin/csh -f
# script to make directories and links for an architecture
# $Id$

if (! $?ARCH ) then
	echo The environment variable ARCH must be set.
	exit 1
endif

mkdir bin.$ARCH lib.$ARCH obj.$ARCH
cd obj.$ARCH
ln -s ../src/makefile .
foreach x (domains interp kernel pigiRpc tests preproc)
	mkdir $x
	cd $x
	ln -s ../../src/$x/makefile .
	if (-r ../../src/$x/make.template) ln -s ../../src/$x/make.template .
	cd ..
end

foreach x (xgraph filters)
	mkdir $x
	cd $x
	ln -s ../../src/$x/Makefile .
	cd ..
end

cd filters
foreach x (optfir wfir)
	mkdir $x
	cd $x
	ln -s ../../../src/filters/$x/Makefile .
	cd ..
end
cd ..

# EXPDOMAINS = experimental domains
# EXPDOMAINS = capsim bdf
set EXPDOMAINS=

cd domains
foreach x (sdf ddf de thor $EXPDOMAINS)
	mkdir $x
	cd $x
	ln -s ../../../src/domains/$x/makefile .
	foreach y (kernel stars)
		mkdir $y
		cd $y
		ln -s ../../../../src/domains/$x/$y/{make.template,makefile} .
		cd ..
	end
	cd ..
end

# At this point, we are in obj.$ARCH/domains.

# special case: thor/pepp
mkdir thor/pepp
cd thor/pepp
ln -s ../../../../src/domains/thor/pepp/{make.template,makefile} .
cd ../..

#special case: cg/loopScheduler
mkdir cg/loopScheduler
ln -s ../../../../src/domains/cg/loopScheduler/{make.template,makefile} .
cd ../..

#special case: sdf/expgraph
mkdir sdf/expgraph
ln -s ../../../../src/domains/sdf/expgraph/{make.template,makefile} .
cd ../..

# This is for the makefile
cd ../..
touch obj.$ARCH
