##########################################################################
# @Version: $Id$
# @Author: H. John Reekie
#
# @Copyright (c) 1996 The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#                                                         COPYRIGHTENDKEY
##########################################################################


#######################################################################
#### AsPoint
#
# A shape for items with a single pair of coordinates.
#
class ::tycho::AsPoint {
    inherit ::tycho::Shape

    ###################################################################
    ####                         public procs                      ####

    # Get one or more aspects of an item
    proc aspect {id canvas slate args}

    # Attach a set of grapples to an item
    proc grapple {id canvas slate interactor args}

    # Generate an error, since point objects cannot be reshaped
    proc reshape {id canvas slate x y args}

    # Generate an error, since point objects cannot be reshaped
    proc reshapeclick {id canvas slate x y args}

    # Generate an error, since point objects cannot be reshaped
    proc reshapedrag {id canvas slate x y}

    # Generate an error, since point objects cannot be reshaped
    proc reshaperelease {id canvas slate x y}
}


#######################################################################
#### aspect
#
# Return the value of an aspect. The only valid aspect is "origin."
#
body ::tycho::AsPoint::aspect {id canvas slate args} {
    set coords [$slate coords $id]
    set result {}

    if { $args == "" } {
    	return [list "origin"]
    } else {
	foreach aspect $args {
	    switch -exact $aspect {
		"origin" {
		    eval lappend result $coords
		}
		default {
		    error "Invalid aspect \"$aspect\" of line shape"
		}
	    }
	}
    }
    return $result
}

#######################################################################
#### reshape
#
body ::tycho::AsPoint::reshape {id canvas slate x y args} {
    error "Point objects cannot be reshaped"
}

#######################################################################
#### reshapeclick
#
body ::tycho::AsPoint::reshapeclick {id canvas slate x y args} {
    error "Point objects cannot be reshaped"
}

#######################################################################
#### reshapedrag
#
body ::tycho::AsPoint::reshapedrag {id canvas slate x y} {
    error "Point objects cannot be reshaped"
}

#######################################################################
#### reshaperelease
#
body ::tycho::AsPoint::reshaperelease {id canvas slate x y} {
    error "Point objects cannot be reshaped"
}
