.\" $Id$
.NA delayVsServer
.SD
Illustrate the difference between the
.c Delay
and
.c Server
blocks.
The
.c Delay
passes the input events to the output with a fixed time offset.
The
.c Server
accepts inputs only after the previous inputs have been served,
and then holds that input for a fixed offset.
.DE
.EQ
delim off
.EN
.LO "$PTOLEMY/src/domains/de/demo"
.EQ
delim $$
.EN
.SV $Revision$ $Date$
.AL "E. A. Lee"
.LD
A deterministic
.c Delay
block (with delay 1.0)
and a deterministic
.c Server
block (with service time 1.0) are fed the same Poisson counting process.
.IE Delay
.IE Server
The Poisson counting process is generated by feeding a
.c Ramp
star with Poisson arrivals.
.IE "Poisson counting process"
The output plot shows that the
.c Server
does not accept new inputs
while it is serving previous inputs, and hence may delay
some samples more than the
.c Delay
block.
Inputs to the server are queued on the input Geodesic, which
has effectively infinite capacity.
.SA
Delay,
Ramp,
Poisson,
Server.
.ES
