.\" $Id$
.NA statistics
.SD
Demonstrates how to obtain the statistics of the input data
.DE
.SV 1.1 "December 3, 1990"
.AL "S. Ha"
.LD
.IE Statistics
.IE StopTimer
.IE "Printer, de"
.IE RanGen
This demo illustrates how to obtain the statistics of the input
data in time.  A sequence of random numbers is generated by
.c RanGen
block, the time interval of which is exponentially distributed (
.c Poisson
block).  The distribution of the random number can be chosen among
uniform, exponential, and normal by setting the parameters of the
.c RanGen
block.
The statistics of the input data is produced when the demand input
of the
.c Statistics
block is entered.  We calculate the time average and time variance
of the input data. 
In this demo, we produce the statistics at the
end of the simulation run.  The
.c StopTimer
block generates an event at the stop time of the DE Scheduler.
We may restarts calculating the statistics from an arbitrary time origin
,if we want, by giving the reset signal to the
.c Statistics 
block.  Note that we connect a
.c Null
block to the reset input of the
.c Statistics
block.  The time origin of the statistics in this demo is zero by default.
The statistics of the input are fed into the
.c Printer
block, which stores the result in the file we may specify.  This demo
will print out the result in the console.
.pp
This demonstration introduces some interesting blocks in DE domain :
.c Null ,
.c StopTimer ,
.c RanGen ,
.c Statistics ,
and
.c Printer .
Connect the
.c Null 
block to any unused input port
of a block.
We can use the
.c Statistics
block to obtain the statistics of the queue size in a queueing system.
The
.c StopTimer 
block might be used to specify when to
sample the output data of the DE domain if the DE domain
resides in a 
.c Wormhole
of a untimed domain like SDF.
.SA
Null,
Printer,
RanGen,
Statistics,
StopTimer.
.ES
