# Makefile for sdf/dsp
# Copyright (c) 1990 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# @(#)make.template	1.1	10/22/92
#
# Important!  Do not run this makefile while in ~ptolemy/src/domains/cg.
# Instead run in from ~ptolemy/obj.$ARCH/domains/cg (through the symbolic
# link) -- that way a separate directory containing, say, Sun-3 and Sun-4
# objects can be maintained.

include ../../../../subdomain.mk

DIRS = stars

ME = sdf/dsp

