# Makefile for cgc/targets/NOWam (Network Of Workstations with active messages)
# Copyright (c) 1996 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# @(#)makefile	1.3 1/30/96
#
# Important!  Do not run this makefile while in 
# $PTOLEMY/src/domains/cgc/targets/NOWam.
# Instead run in from ~$PTOLEMY/obj.$PTARCH/domains/cgc/targets/NOWam
# (through the symbolic link) -- that way a separate directory containing,
# say, Sun-3 and Sun-4 objects can be maintained.

# subdomain.mk reads MYVPATH
MYVPATH = ../../../../../../

include ../../../../../mk/subdomain.mk

DIRS = NOWam libudpam

ME = cgc/targets/NOWam

