/* This file contains a table of the official DE_CONTRIB stars.  Its purpose is
 * to force the linker to retrieve the corresponding stars from their
 * library.
 *
 * DO NOT EDIT THIS FILE!  It is generated automatically from the
 * make.template file's definition of PL_SRCS.
 */

#define STR extern char *

 STR star_nm_DECIR_uldl;
 STR star_nm_DEMobile_Station;
 STR star_nm_DEParallel2Serial;
 STR star_nm_DEWeighted_List;
 STR star_nm_DEWiNeS_Tcl_Animation;
 STR star_nm_DEcell_list;
 STR star_nm_DEpos_generator;
 STR star_nm_DEpropag_uldl;
 STR star_nm_DErrmanager_uldl;
 STR star_nm_DEDynMapBase;
 STR star_nm_DEDynMap;
 STR star_nm_DEDynMapGr;
 STR star_nm_DEDynMerge;
 STR star_nm_DEDynForkBase;
 STR star_nm_DEDynForkInt;
 STR star_nm_DEDynFork;
static char** nm_table[] = {
 &star_nm_DECIR_uldl,
 &star_nm_DEMobile_Station,
 &star_nm_DEParallel2Serial,
 &star_nm_DEWeighted_List,
 &star_nm_DEWiNeS_Tcl_Animation,
 &star_nm_DEcell_list,
 &star_nm_DEpos_generator,
 &star_nm_DEpropag_uldl,
 &star_nm_DErrmanager_uldl,
 &star_nm_DEDynMapBase,
 &star_nm_DEDynMap,
 &star_nm_DEDynMapGr,
 &star_nm_DEDynMerge,
 &star_nm_DEDynForkBase,
 &star_nm_DEDynForkInt,
 &star_nm_DEDynFork,
};
