function PtSetStarFigures(handle)
%PtSetStarFigures 
%       PtSetStarFigures(handle) will cause all newly generated
%	figures (images, plots, etc.) to be associated with handle.
%	Ptolemy calls this function to attach the name of a Matlab
%	star to all plots generated by that star.
%
%       See also PtCloseStarFigures.

%
%       $Id$
%

%       Author: B. L. Evans
%       (c) Copyright 1994 by the Regents of the University of California

set(0, 'DefaultFigureUserData', handle);
end
