# Test the Polygon shape
#
# @Author: John Reekie
# 
# @Version: $Id$
#
# @Copyright (c) 1997 The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
#######################################################################

if {[string compare test [info procs test]] == 1} then { 
    source [file join $TYCHO kernel test testDefs.tcl]
} {}

if {[string compare test [info procs _slate]] == 1} then { 
    source [file join $TYCHO editors slate test defs.itcl]
} {}

if { ! [::info exists SHORTTIME] } {
    set SHORTTIME 50
}
#set VERBOSE 1


#######################################################################
#### Define a proc to create a polygon
proc _polygon {} {
    global p
    _clean
    set p [.s create polygon 50 50 150 50 150 150 100 100 50 150 50 50 \
	    -width 2 -fill "" -outline blue \
	    -tags foo]
}

#######################################################################
#### _aspect

#######################################################################
#### _grapple

#######################################################################
#### _reshape

#######################################################################
#### _reshapeclick
#### _reshapedrag
#### _reshaperelease
#
# These methods are tested as a set.
#
set delta 40
set i 0

foreach a {vertex-0 vertex-1 vertex-2 vertex-3 vertex-4} {
    incr i
    _polygon
    test Polygon-_reshapeclick.$i \
            "Reshape a polygon item, no ghosting, $a" {
        _interact ::tycho::Polygon::_reshape $p 1 1 $delta -aspects $a
    } [_finally2 ::tycho::Polygon::reshape $p 1 1 $delta $a]
}

foreach a {vertex-0 vertex-1 vertex-2 vertex-3 vertex-4} {
    incr i
    _polygon
    test Polygon-_reshapeclick.$i \
            "Reshape a polygon item by tag, with ghosting, $a" {
        _interact ::tycho::Polygon::_reshape foo 1 1 $delta \
                -aspects $a -ghost 1
    } [_finally2 ::tycho::Polygon::reshape foo 1 1 $delta $a]
}

incr i
_polygon
test Polygon-_reshapeclick.$i {Reshape multiple aspects, no ghosting} {
    _interact ::tycho::Polygon::_reshape $p 1 1 $delta \
            -aspects {vertex-0 vertex-2}
} [_finally2 ::tycho::Polygon::reshape $p 1 1 $delta vertex-0 vertex-2]

incr i
_polygon
test Polygon-_reshapeclick.$i {Reshape multiple aspects, with ghosting} {
    _polygon
    _interact ::tycho::Polygon::_reshape $p 1 1 $delta \
            -aspects {vertex-1 vertex-3} -ghost 1
} [_finally2 ::tycho::Polygon::reshape $p 1 1 $delta vertex-1 vertex-3]


##########################################################################
#### aspect

#######################################################################
#### center

#######################################################################
#### reshape

##########################################################################
#### reverse

##########################################################################
#### flip

##########################################################################
#### flop

##########################################################################
#### rotate
