# A control sub-panel with ten control sliders for a graphic eq.
#
# @Author: John Reekie and Sunil Bhave
#
# @Version: $Id$
#
# @Copyright (c) 1996-1997 The Regents of the University of California.
# All rights reserved.
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
#
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
#                                        PT_COPYRIGHT_VERSION_2
#                                        COPYRIGHTENDKEY
#######################################################################


#######################################################################
#### ParametricEq
# A small panel that contains ten sliders for parametric
# equalisation. The names of the stars controlled can be set by the
# *-stars* option -- each entry in this list is the prefix of a
# set of star names, where the rest of the names are in the list
# *{31 63 125 250 500 1k 2k 4k 8k 16k}*. This must be set before
# calling the control panel add{} method. The default is *{left right}*.
#
class ::tycho::ParametricEq {
    inherit ::tycho::ControlSubpanel

    constructor {args} {}
    destructor {}
    
    ###################################################################
    ####                            options                       ####

    # The prefix of the stars to control
    itk_option define -star stars Stars {left right}

    ###################################################################
    ####                         public methods                    ####

    # Request the widget to connect its controls
    method requestConnect {}
}

#######################################################################
#### constructor
#
body ::tycho::ParametricEq::constructor {args} {
    # Create a frame so we can have nice reliefs
    itk_component add frame {
        frame $itk_interior.frame \
                -borderwidth 2 \
                -relief sunken
    }
    pack $itk_component(frame) -side left
    
    # Create the sliders for each band
    foreach {freq} {31 63 125 250 500 1k 2k 4k 8k 16k} {
    	itk_component add $freq {
 	      	eval ::tycho::Slider $itk_interior.$tag \
 	      		-label $freq \
 	    		-from -10 \
 	    		-to 10 \
 	    		-resolution 1 \
 	    		-digits 0
    	} {
        	keep -cursor -background
    	}
    	pack $itk_component($freq) -side left -in $itk_component(frame)
	}
    # Initialise options.
    eval itk_initialize $args
}

######################################################################
#### requestConnect
#
# Make the connection to the stars with prefixes given by *-stars*.
#
body ::tycho::ParametricEq::requestConnect {} {
	foreach star $itk_option(-stars) {
		foreach freq {31 63 125 250 500 1k 2k 4k 8k 16k} {
	    	connect $freq star$freq gain
		}
	}
}
