#!/bin/csh -f
# 
# Version: $Id$

lpr -P$PRINTER users_manIX.ps
lpr -P$PRINTER references.ps
lpr -P$PRINTER ptglossary.ps
lpr -P$PRINTER filter.ps
lpr -P$PRINTER x.ps
lpr -P$PRINTER installation.ps
lpr -P$PRINTER xgraph.ps
lpr -P$PRINTER vem.ps
lpr -P$PRINTER documents.ps
lpr -P$PRINTER silage.ps
lpr -P$PRINTER sproc.ps
lpr -P$PRINTER cg96.ps
lpr -P$PRINTER cg56.ps
lpr -P$PRINTER cgc.ps
lpr -P$PRINTER cg.ps
lpr -P$PRINTER cp.ps
lpr -P$PRINTER mq.ps
lpr -P$PRINTER thor.ps
lpr -P$PRINTER de.ps
lpr -P$PRINTER bdf.ps
lpr -P$PRINTER ddf.ps
lpr -P$PRINTER hof.ps
lpr -P$PRINTER sdf.ps
lpr -P$PRINTER domains.ps
lpr -P$PRINTER ptcl.ps
lpr -P$PRINTER pigi.ps
lpr -P$PRINTER overview.ps
lpr -P$PRINTER foreword0.5.2.ps
lpr -P$PRINTER users_manTOC.ps
lpr -P$PRINTER title.ps
