#! /bin/sh
#
###################  DO NOT EDIT  ##########################
# This shell script was automatically generated.
###################  DO NOT EDIT  ###########################
#
PTOLEMY=${PTOLEMY-`csh -c 'echo ~ptolemy'`}; export PTOLEMY
PATH=$PTOLEMY/octtools/bin.$ARCH:$PATH; export PATH
domain=CG56
domainpath=cg56
# This file was auto-generated by kennard on Thu Oct 22 15:59:55 PDT 1992.
# The script gen-rename generated this file from config file cg56.conf
# Shell script to move ptlang files and OCT icon facets.
# This should be invoked in the top-level directory for the domain.
if [ ! -d icons -o ! -d stars ] ; then
    echo "Missing the icons and/or stars directory."
    echo "Invoke this script in the toplevel directory for the domain."
    exit 0
fi
moveprog=/tmp/moveprog$$
cat - > $moveprog <<\BEOF
# This script segment assumes that src,tgt,tgtdir have already
# been defined.
tgtdir=${tgtdir:=.}
srcbase=${domain}$src; srcpl=$srcbase.pl
tgtbase=${domain}$tgt; tgtpl=$tgtbase.pl
if [ -n "$tgtdir" ] ; then
    mkdir $tgtdir $tgtdir/stars $tgtdir/stars/SCCS $tgtdir/icons 2> /dev/null
fi
if [ ! -f stars/$srcpl ] ; then
    echo Warning: ptlang $srcpl missing
else
    echo moving stars/$srcpl '-->' $tgtdir/stars/$tgtpl
    mv -i stars/$srcpl $tgtdir/stars/$tgtpl
    if [ -f stars/SCCS/s.$srcpl ] ; then
	mv -i stars/SCCS/s.$srcpl $tgtdir/stars/SCCS/s.$tgtpl
    fi
    if [ -f stars/SCCS/p.$srcpl ] ; then
	mv -i stars/SCCS/p.$srcpl $tgtdir/stars/SCCS/p.$tgtpl
    fi
    rm -f stars/$srcbase.cc stars/$srcbase.h
fi
for icon in icons/$src icons/$src.*; do
    if [ ! -d "$icon" ] ; then continue ; fi
    newname=`echo $icon | sed -e "s+/$src+/$tgt+"`
    if [ -f $tgtdir/$newname -o -d $tgtdir/$newname ] ; then
	echo Warning: icon $tgtdir/$newname already exists...skipping
    else
    	echo moving icon $icon '-->' $tgtdir/$newname
    	mv -i $icon $tgtdir/$newname
    fi
done
BEOF

src=Allpass; tgt=Allpass; tgtdir=dsp; . $moveprog
src=BiQuad; tgt=Biquad; tgtdir=dsp; . $moveprog
src=Comb; tgt=Comb; tgtdir=dsp; . $moveprog
src=DSPlayBQ; tgt=BiquadDSPlay; tgtdir=dsp; . $moveprog
src=FIR; tgt=FIR; tgtdir=dsp; . $moveprog
src=FixDC; tgt=Const; tgtdir=; . $moveprog
src=FixDiff; tgt=Sub; tgtdir=; . $moveprog
src=FixGain; tgt=Gain; tgtdir=; . $moveprog
src=FixImpulse; tgt=Impulse; tgtdir=; . $moveprog
src=FixPad; tgt=Pad; tgtdir=; . $moveprog
src=FixProduct; tgt=Mpy; tgtdir=; . $moveprog
src=FixRamp; tgt=Ramp; tgtdir=; . $moveprog
src=FixRect; tgt=Rect; tgtdir=; . $moveprog
src=FixSum; tgt=Add; tgtdir=; . $moveprog
src=IntMult; tgt=IntMult; tgtdir=junk; . $moveprog
src=IntProduct; tgt=MpyInt; tgtdir=; . $moveprog
src=IntQuantizer; tgt=QuantInt; tgtdir=; . $moveprog
src=IntReadFile; tgt=ReadFileInt; tgtdir=; . $moveprog
src=IntWriteFile; tgt=WriteFileInt; tgtdir=; . $moveprog
src=LMS; tgt=LMS; tgtdir=dsp; . $moveprog
src=LMSGanged; tgt=LMSGanged; tgtdir=dsp; . $moveprog
src=Quantizer; tgt=Quant; tgtdir=; . $moveprog
src=RaisedCos; tgt=RaisedCos; tgtdir=dsp; . $moveprog
rm -f $moveprog
