# Makefile for domains/de/atm
# Copyright (c) 1990-1997 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# @(#)makefile	1.4	04/07/97
#
# Important!  Do not run this makefile while in ~ptolemy/src/domains/mq.
# Instead run in from ~ptolemy/obj.$PTARCH/domains/mq (through the symbolic
# link) -- that way a separate directory containing, say, Sun-3 and Sun-4
# objects can be maintained.

include ../../../../mk/subdomain.mk

DIRS = stars

ME = de/atm

