# Test suite for the Edit class
#
# @Authors: Christopher Hylands
#
# @Version: @(#)testEditItcl.itcl	1.3 04/07/98
#
# @Copyright (c) 1998 The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
#######################################################################

# Make sure that the required packages are loaded
package require tycho.util.tytest
package require tycho.edit.textedit

# We also have to load this helper file
source [file join $env(GUI_LIBRARY) test FileTester.itcl]

#set VERBOSE 1

############################################################################
test EditItcl-1.1 {Evaluate an Itcl file with redefinition warnings off} {
    set view [::tycho::openContext evalTest.itcl]
    set win [$view displayer windowName]
    ::tycho::stylesheet set interaction itclClassRedefinitionWarning 0 
    #puts [$view stylesheet get interaction itclClassRedefinitionWarning]
    $view evaluate
    after $duration removeobj $win 
    evalTest::testProc
} {1}

test EditItcl-1.2 {Evaluate an Itcl method} {
    # Copy the file, evaluate it and run the testProc method
    set tmpFile [::tycho::tmpFileName evalTest .itcl]
    file copy evalTest.itcl $tmpFile
    global tcl_platform
    if {$tcl_platform(platform) == "unix"} {
        catch {exec chmod u+w $tmpFile}
    }

    set view [::tycho::openContext $tmpFile]
    set win [$view displayer windowName]
    ::tycho::stylesheet set interaction itclClassRedefinitionWarning 0 
    $view evaluate  
    set res1 [evalTest::testProc]

    # Substitute 'set a 2' for 'set a 1'
    $view findAll toBeSubstituted 0 0 0 {set a 1} 0.0 end {}
    set TY_TEST_MODAL {
        {%0 invoke yes}
    }
    $view replaceAll toBeSubstituted {set a 2}
    set findOneReturn [$view findOne 0 0 0 0 {set a 2} 0.0 end {}]
    $view seeFragment [lindex $findOneReturn 0]
    $view markUnmodified

    # reevaluate the testProc method, note that the results is now 2
    ::tycho::stylesheet set interaction itclClassRedefinitionWarning 1
    $view evaluateConstruct
    set res2 [evalTest::testProc]
    after $duration removeobj $win 
    after $duration file delete $tmpFile
    list $res1 $res2
} {1 2}


