# Makefile for SR domain support
# Copyright (c) 1990 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# Programmer:  E. A. Lee and D. Niehaus
# $Id$
#
# Important!  Do not run this makefile while in $PTOLEMY/src/domains/sr.
# Instead run in from $PTOLEMY/obj.$PTARCH/domains/sr (through the symbolic
# link) -- that way a separate directory containing, say, sun4 or mips
# objects can be maintained.

include ../../../mk/topdomain.mk

DIRS = kernel stars

ME = sr

