# Version $Id$
# Copyright 1992-1994 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# Programmer:  T. M. Parks
#
# Makefile for MTDF domain support

include ../../../mk/topdomain.mk

DIRS = kernel stars

ME = pn
