.\" $Id$ 
.NA "Sim56Target"
.SD
Sim56Target is a architecture description for the Motorola 56000
simulator.
.SE
.EQ
delim off
.EN
.LO "$PTOLEMY/src/domains/cg56/targets"
.EQ
delim $$
.EN
.SV $Revision$ $Date$ 
.AL "J. Buck and J. Pino"
.SH
.NE
\fIRun Sim-CG56?\fR : If yes, compile and then simulate the application 
with the Motorola 56000 simulator.
.DF "YES"
.NE
\fIPlot file name\fR : File to plot with xgraph, after simulation ends. 
It will only plot if file is generated by the universe.
.DF "outfile.sim"
.NE
\fIPlot title\fR : Title to use for the plot.
.DF "Simulator output"
.NE
\fIPlot options\fR : Options to use with xgraph.
.DF ""
.NE
\fIInteractive Simulation\fR : If yes, the simulator window is shown; 
otherwise, run the simulator in the backgroud.
.DF "YES"
.ET:
.LD
.pp
This target is used for generating and running assembly code for the Motorola
56000 simulator.  To use it, select \fBSim-CG56\fR in the pigi \fBedit-target\fR menu.
To plot an output use one of the WriteFile stars.  If a interactive
simulation is selected, the program is automatically loaded iton the 
simulator and is executed.   At this point the user can examine any of 
the registers or restart the application.
.pp
.Ie "target, multiple-inheritance"
Both of Sim56Target and Sim96Target are very similar and have been
defined using the \fIC++\fR concept of \fImultiple-inheritance\fR.
.SA
WriteFile (CG56 Star)
WriteFileInt (CG56 Star)
CG56Target
.ES
