# Definition of a Ptlang context-sensitive editor.
#
# @Author: Edward A. Lee
#
# @Version: $Id$
#
# @Copyright (c) 1995-%Q% The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
#######################################################################

#######################################################################
#### EditPtlang
# This class defines a window that provides an emacs-like editor
# specialized for editing ptlang files. Ptlang is the preprocessor
# language used to define stars in Ptolemy. This class colorizes the
# code, identifying comments and ptlang keywords, automatically indents
# the code, and fills blocks of comments.  It is derived from the C++
# editor, and hence inherits all its features.
#
class ::tycho::EditPtlang {
    inherit ::tycho::EditCpp

    constructor {args} {}
    destructor {}

    ###################################################################
    ####                            options                        ####

    itk_option define -star star Star {}

    ###################################################################
    ####                         public methods                    ####

    # Open a help window.
    method help {}

    ###################################################################
    ####                  protected methods                        ####

    # Return the name of the type of text widget to use (EditPtlangText).
    protected method textWidget {} {return ::tycho::EditPtlangText}
}

#######################################################################
#### -star configuration
# The argument to -star should be a two element list that consists
# of a domain name and a star name.  The domain name should be capitalized.
# for example, the following code will open up the SDF Cosine .pl file 
# <tcl><pre>
#  ::tycho::EditPtlang .e -star {SDF Cos}
#  .e centerOnScreen
# </pre><tcl>
configbody ::tycho::EditPtlang::star {
    global PTOLEMY
    set domainStarList $itk_option(-star)
    if {$domainStarList != {} } {
        set domain [lindex $domainStarList 0]
        set star [lindex $domainStarList 1]
        set file [file join $PTOLEMY src domains [string tolower $domain] \
                stars $domain$star.pl]
        puts $file
        if [file exists $file] {
            configure -file $file
        } else {
            # Ok, the star was not in domain/stars, so look elsewhere
            set file [ glob -nocomplain \
                    [file join $PTOLEMY src domains [string tolower $domain] \
                    * stars $domain$star.pl ]]
            puts $file
            switch [llength $file] {
                0 {error "Could not find a source file for $star in $domain"}
                1 {configure -file $file} 
                default {error "More than one possibility for $star in $domain\n
                $possibleFile"}
            }
        }
    }
}

###################################################################
#
body ::tycho::EditPtlang::constructor {args} {
    global PTOLEMY
    eval itk_initialize $args

    # Stuff for the help menu
    addMenuItem "Ptolemy Universes" Help -underline 0 \
            -command "::tycho::File::openContext \
	    \[file join \$env(PTOLEMY) tycho typt lib PtolemyFacets.fst\]"

    addMenuItem "Star/Demo Xref" Help -underline 11 \
            -command "::tycho::File::openContext \
            [file join $PTOLEMY doc star-demo-index index.html]"

    addMenuItem "Ptolemy stars" Help -underline 0 \
            -command "::tycho::File::openContext \
	    \[file join \$env(PTOLEMY) src domains starHTML.idx.fst\]"
}

###################################################################
#### help
# Open a window with help on the current widget.
#
body ::tycho::EditPtlang::help {} {
    global ::TYCHO
    ::tycho::File::openContext \
	    $TYCHO/editors/textedit/doc/usersGuides/EditPtlangHelp.html
}
