#! /bin/csh -f
# script to make directories and links for an architecture
# $Id$

if (! $?ARCH ) then
	echo The environment variable ARCH must be set.
	exit 1
endif

mkdir bin.$ARCH lib.$ARCH obj.$ARCH
cd obj.$ARCH
ln -s ../src/makefile .
foreach x (domains interp kernel pigiRpc tests preproc)
	mkdir $x
	cd $x
	ln -s ../../src/$x/makefile .
	if (-r ../../src/$x/make.template) ln -s ../../src/$x/make.template .
	cd ..
end

mkdir xgraph
cd xgraph
ln -s ../../src/xgraph/Makefile .
cd ..

cd domains
foreach x (sdf ddf de capsim)
	mkdir $x
	cd $x
	ln -s ../../../src/domains/$x/makefile .
	foreach y (kernel stars)
		mkdir $y
		cd $y
		ln -s ../../../../src/domains/$x/$y/{make.template,makefile} .
		cd ..
	end
	cd ..
end

# This is for the makefile
cd ..
touch obj.$ARCH
