#!/bin/csh
# Version: $Id$
# Copyright (c) 1996-1997 The Regents of the University of California.
# All Rights Reserved.
#
# loadc50
# script to load files with TI's DSK loader(dsk5l.exe)
# Uses xdos to run dsk5l.exe.  The person running it must be root to
# mount/unmount the dos partition.
# This script was tested on a machine running linux(red-hat 3.0.3 
# diistribution) with dosemu-0.63.1.33 installed.
# Written by Luis Gutierrez.
#
# Converted from csh to sh by Brian L. Evans

# User's home directory.
homedir=/root

# User's dos partition.
dospartition=/dos/c

# The root path of DOS drive where DSK files and DOS binaries are stored.
dosroot=c:

# The DOS directory(relative to dosroot\)where the *.asm and *.dsk files 
# are stored. Replace the \ in the DOS path with \\.
dsksrc=dsk\\src

# The DOS directory(relative to dosroot) where the DSK 
# executables(dsk5a.exe, dsk5l.exe) are stored.  
# Replace the \ in the DOS path with \\.
dskbin=dsk

# The file used to temporarily save autoexec.emu
autoexecsave=autoexec.bak

cd $dospartition
mv autoexec.emu $autoexecsave

# The text between the first xxxx and the second xxxx will be
# piped to unix2dos and will end up in autoexec.emu.

unix2dos  > $dospartition/autoexec.emu << xxxx
path $dosroot\\$dskbin;$dosroot\\dos
cd $dosroot\\$dsksrc
dsk5l.exe  $1:t
exitemu
xxxx
cd $homedir

# Unmount DOS partition to run xdos
umount $dospartition
xdos

# After running xdos mount DOS partition
mount -t msdos /dev/sda1 $dospartition

# Restore autoexec.emu
cd $dospartition
mv -f $dospartition/$autoexecsave  $dospartition/autoexec.emu
