#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: Widget tree in [incr Widgets]
# @(#)widgettree	1.1 07/30/97
# ----------------------------------------------------------------------
#\
exec itkwish -f "$0" ${1+"$@"}

source widgettree.itk

# The first widget is a simple expanding widget that doesn't
# do anything other than demonstrate how the Widgettree
# is dynamically constructed. The tree is packed into a
# scrolledframe widget, as it should be in order to prevent
# nasty window resizing as the widget is used.

proc expand {widget tag} {
    puts "Adding to $tag"
    $widget add node $tag.foo -text $tag.foo
    $widget add node $tag.bar -text $tag.bar
}

catch {delete object .f}
iwidgets::scrolledframe .f \
        -hscrollmode dynamic -vscrollmode dynamic \
        -height 200 -width 150

set w [.f childsite].w
iwidgets::widgettree $w -createcommand "expand $w"
$w add node foo -text foo
$w add node bar -text bar
grid $w -sticky nw

pack .f -fill both -expand on

# The second widget illustrates how arbitrary widgets
# can be included as leaves of the tree. The expand
# command is set to call a proc that creates a preference
# setting panel.

proc mkPref {win tag} {
    switch -exact $tag {
	"size" {
	    $win create radiobox size -options {
		rename -labelfont -font font Font
	    }
	    set r [$win component $tag]

	    $r add small -text "Small"
	    $r add med -text "Medium"
	    $r add large -text "Large"
	    $r add xlarge -text "Biggie"
	    $r select med
	}
	"address" {
	    set f [$win create frame address]

	    foreach {name text} {
		name "Name" addr "Street" city "City, State" email "E-mail"
	    } {
		entryfield $f.$name -labeltext $text
		grid $f.$name -sticky e
	    }
	}
    }
}

catch {delete object .g}
iwidgets::scrolledframe .g \
        -hscrollmode dynamic -vscrollmode dynamic \
        -height 200 -width 150

set v [.g childsite].w
iwidgets::widgettree $v -createcommand "mkPref $v"
$v add node size -text Size
$v add node address -text Address
grid $v -sticky nw

pack .g -fill both -expand on



wm deiconify .

