# Ptolemy Welcome Message window.
#
# @Author: Edward A. Lee
#
# @Version: @(#)PtWelcomeMessage.itcl	1.19   04/24/98
#
# @Copyright (c) 1996-1999 The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
##########################################################################

##########################################################################
#### ptkStartupMessage
# If the user has not disable the welcomeWindow, then display it.
#
proc ptkStartupMessage {{version ""} {binary ""}} {
    # Only bring up the welcomeWindow if the user has not disabled it.
    if {[::tycho::stylesheet get interaction welcomeWindow]} { 
	ptkStartupMessageAlways $version $binary
    }
}

##########################################################################
#### ptkStartupMessageAlways
# Ignore the user's preferences and bring up the welcomeWindow.
#
proc ptkStartupMessageAlways {{version ""} {binary ""}} {
    set nm [::tycho::autoName .ptwelcome]
    uplevel #0 [list ::tycho::PtWelcomeMessage $nm \
	    -version $version \
	    -executable $binary \
	    -persistent 0]
    $nm centerOnScreen
}

##########################################################################
#### PtWelcomeMessage
# A startup message window.
#
class ::tycho::PtWelcomeMessage {
    inherit ::tycho::HTMLMessage

    # Specify the version of the executable that we are running.
    itk_option define -version version Version ""

    # Specify the actual executable file that we are running.
    itk_option define -executable executable Executable ""

    # Specify whether the window should destroy itself after a timeout.
    itk_option define -persistent persistent Persistent 1

    constructor {args} {}

    # Indicator of whether the gif image has been created.
    private variable ptgifexists 0
}

##########################################################################
#### constructor
#
body ::tycho::PtWelcomeMessage::constructor {args} {

    global ::TYCHO ::PTOLEMY

    # If the user is on a slow network, then don't show the image
    if {![::tycho::stylesheet get system slowNetwork] } {
	# An option -palette 3/3/2 below restricts the palette,
	# but it is better to restrict it in the source.
	if {!$ptgifexists} {
	    image create photo ptgif \
		    -file $TYCHO/typt/kernel/img/ptolemyWelcome.gif
	}
	configure -image ptgif
    }

    # Pack the copyright button.
    addButton copyright -text "Copyright" -command \
	    "::tycho::File::openContext $PTOLEMY/copyright"

    # Pack the introduction button.
    addButton intro -text "Home Page" -command \
	    "::tycho::File::openContext $PTOLEMY/doc/html/index.html"

    # Process any unevaluated arguments.
    eval itk_initialize $args

    # Arrange for destruction, if appropriate.
    if {!$itk_option(-persistent)} {
	after 40000 [code [list catch [code delete object $this]]]
    }

    # Construct the HTML message that forms the welcome message.
    append html "<body bgcolor=grey90>"
    append html "<center>"
    append html "<color value=firebrick><h1>Welcome to Ptolemy</h1></color>"
    if {$itk_option(-version) != {}} {
	append html "$itk_option(-version)"
    }
    if {$itk_option(-executable) != {}} {
	append html \
		{<br>Executable you are running:<br>} \
		$itk_option(-executable)
    }
    append html "<p>" \
	    "Copyright \251 1990-1999, " \
	    {Regents of the University of California<br>} \
	    {- All rights reserved -<br>} \
	    "<a href=$TYCHO/copyright>See the copyright notice, " \
	    {limitation of liability,<br>} \
	    {and disclaimer of warranty provisions</a>}

    append html "<h1><a href=$PTOLEMY/doc/html/index.html>" \
	    {Introduction to Ptolemy</a></h1>}

    configure -textwidth 60
    configure -textheight 17
    configure -scrollbar 0
    configure -title "Welcome to Ptolemy"
    insertData $html
}
