# Makefile for C50 domain support
# Copyright (c) 1990 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# Programmer: A. Baensch
# Created: 14 April 1995
# Version: $Id$
#
# Important!  Do not run this makefile while in $PTOLEMY/src/domains/cg32.
# Instead run in from $PTOLEMY/obj.$ARCH/domains/cg32 (through the symbolic
# link) -- that way a separate directory containing, say, sun4 or mips
# objects can be maintained.

include ../../../mk/topdomain.mk

DIRS = kernel stars dsp demo targets doc icons

ME = c50

