# Subclass of Resource
# 
# @Author: Kevin Chang
#
# @Version: $Id$
# 
# @Copyright (c) %Q% The Regents of the University of California.
# All rights reserved.
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
#
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
#                                        PT_COPYRIGHT_VERSION_2
#                                        COPYRIGHTENDKEY
#######################################################################

#######################################################################
#### ResourceHTTP
#
#
class ::tycho::ResourceHTTP {
    inherit ::tycho::Resource

    constructor {args} {}
    destructor {}

    #####################################################################
    ####                          options                            ####

    ###################################################################
    ####                         public methods                    ####

    # Close the resource
    method close {}

    # Return the content type of the current file
    method contenttype {}

    # Test if a given resource exists
    method exists {path}

    # Return the current file type 
    method filetype {}

    # Read a string from a streamable resource 
    method gets {}

    # Return files at a given path
    method glob {path}

    # Return true if a given path is a file
    method isfile {path}

    # Open a new resource
    method new {{path {}}}

    # Open the resource
    method open {path {mode "r"}}

    # Get the current full resource path
    method path {}

    # Write a string to a streamable resource 
    method puts {}

    # Return a string containing the data in a streamable resource 
    method read {}

    # Return true if a given resource is readable
    method readable {path}

    # Source a streamable resource as a Tcl script
    method source {{path {}}}

    # Get the status of a resource
    method stat {path varName}

    # Return 1 if this resource is streamable
    method streamable {}

    # Return true if a resource is writable
    method writable {{path {}}}

    ###################################################################
    ####                      public variables                     ####

    # Used with httpget
    public variable statusVariableName {}

    ###################################################################
    ####                         protected methods                 ####

    # Opening an HTTP connection and return the tmp HTTP cache file name.
    method httpget {}

    # This is called by file event handler, from httpget.
    method httpread {fd tmpfd}

    # Set the global http status to "running" or "normal" or "abnormal"
    method httpsetstatus {status}

    # Wait until httpget is done.
    method httpwait {}

    ###################################################################
    ####                        protected variables                ####

    # The full name of the current file (or directory)
    #protected variable currentFile

    # The name of the host name. Format is:<br>
    # <tt>HTTP://$hostname$path:$port</tt>
    protected variable hostname {}
    
    # The name of path in the hostname
    protected variable path /

    # The name of the HTTP port. Default is 80
    protected variable port 80

    # The index of the get
    protected variable idx 0

    # Whether we are getting the header or not (header mode or body mode)
    protected variable isheader 1

    # FIXME: need to find out where to collect protocols that Tycho
    # understands:
    protected variable accept {text/*}

    ###################################################################
    ####                         private variables               ####
}


#######################################################################
#### constructor
#
body ::tycho::ResourceHTTP::constructor {args} {
    eval configure $args
}

#######################################################################
#### destructor
#
body ::tycho::ResourceHTTP::destructor {} {
    close
}

#########################################################################
#########################################################################
####                      public methods                             ####

#####################################################################
#### close
body ::tycho::ResourceHTTP::close {} {
    
}

#####################################################################
#### contenttype
body ::tycho::ResourceHTTP::contenttype {} {

}

#####################################################################
#### exists
body ::tycho::ResourceHTTP::exists {[ath} {

}

#####################################################################
#### filetype
body ::tycho::ResourceHTTP::filetype {} {
    return "http"
}

#####################################################################
#### gets
body ::tycho::ResourceHTTP::gets {} {

}

#####################################################################
#### glob
body ::tycho::ResourceHTTP::glob {path} {

}

#####################################################################
#### isfile
body ::tycho::ResourceHTTP::isfile {path} {
    return 0
}

#####################################################################
#### new
body ::tycho::ResourceHTTP::new {{path {}}} {
    set new [[info class] [::tycho::autoName resource]]
    if { $path == "" } {
	$new open $currentFile
    } else {
	$new open $path
    }
    return $new
}

#####################################################################
#### open
# URL should be in the following format: 
#
body ::tycho::ResourceHTTP::open {url {mode "r"}} {
    if {$mode!="r"} {
        return -1
    }

    #puts "Going to get url: $url"
    # 
    # The following is verbatim from Surfit: vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
    if {[regexp -nocase {^http://([^/:]*)(:([^/]+))?(.*)} $url match \
            hosttmp optport porttmp pathtmp]} {
        if {$hosttmp!={}} {set hostname $hosttmp} ;# Supply reasonable default
        if {$porttmp!={}} {set port $porttmp}     ;# HTTP default service
        if {$pathtmp!={}} {set path $pathtmp}
    } else {
        # Recover from malformed URL
        if {![string match */* $url]} {
            # Assume only the hostname:port has been given
            regexp {([^:]*)(:(.*))?} $url match \
                    hosttmp optport porttmp
            if {$hosttmp != {}} {set hostname $hosttmp}
            if {$porttmp != {}} {set port $porttmp}
            set path /
        } else {
            error "no hostname given in URL \"$url\""
        }
    }
    # Surfit ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    set cacheFile [httpget]
    ::puts "CACHE: $cacheFile"

    # Read in the cache file
    set fd [::open $cacheFile r]
    ::gets $fd status

}





#####################################################################
#### path
body ::tycho::ResourceHTTP::path {} {
    if {$port!={}} {
        return "HTTP://$hostname$currentPath:$port"
    } else {
        return "HTTP://$hostname$currentPath"
    }
}

#####################################################################
#### read
body ::tycho::ResourceHTTP::read {} {

}

#####################################################################
#### readable
body ::tycho::ResourceHTTP::readable {{path {}}} {
    return 1
}

#####################################################################
#### source
body ::tycho::ResourceHTTP::source {{path {}}} {

}

#####################################################################
#### stat
body ::tycho::ResourceHTTP::stat {path varName} {

}

#####################################################################
#### streamable
body ::tycho::ResourceHTTP::streamable {} {
    return 1
}

#####################################################################
#### writable
body ::tycho::ResourceHTTP::writable {{path {}}} {
    return 0
}

#########################################################################
#########################################################################
####                     protected methods                           ####

#########################################################################
#### httpget
# Opening an HTTP connection. This returns the file name of the 
# temporary HTTP file (later on cache). This method assumes that
# hostname, port, and path are set.
#
body ::tycho::ResourceHTTP::httpget {} {
    # Surfit starts here vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
    if {[catch {socket -async $hostname $port} fd]} {
        unset $fd
        error "Can't open $host, $port"
    }
    # Surfit ends here ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    # Wait until finished reading HTTP file
    set tmpFile [::tycho::tmpFileName Cache].html
    set tmpfd [::open $tmpFile "w"]
    set statusVariableName [::tycho::autoName httpgetStatus]
    set isheader 1    ;# Initially we're getting the header first
    httpStatus $statusVariableName "running"

    # connect now!
    fconfigure $fd -blocking no -translation crlf
    ::puts $fd "GET $path HTTP/1.0\
            User-Agent: Tycho Jr. Beta\
            Accept-Encoding: $accept"
    ::puts $fd ""
    ::flush $fd
    fconfigure $fd -translation auto

    ::tycho::safeUpdate $this
    fileevent $fd w {}
    fileevent $fd r "$this httpread $fd $tmpfd"

    ::puts "File ids are $fd $tmpfd"
    # Wait until the entire http file is here on local drive
    httpwait

    return $tmpFile
}

#########################################################################
#### httpread
# This is called by file event handler, from httpget.
#
body ::tycho::ResourceHTTP::httpread {fd tmpfd} {
    if [eof $fd] {
	catch {::close $fd}
	catch {::close $tmpfd}
        httpStatus $statusVariableName "done"
    } else {
        
	::gets $fd line
        if {$isheader==1} {
            # Header mode
            if {$line=={}} {
                # End of header is denoted by an empty line
                set isheader 0
            } else {
                # Parse the header information:
                #HTTP/1.0 200 Document follows
                #Date: Wed, 21 May 1997 00:54:29 GMT
                #Server: NCSA/1.4.1
                #Content-type: text/html
                #Last-modified: Fri, 16 May 1997 21:18:58 GMT
                #Content-length: 8215
                #
                #HTTP/1.0 302 Found
                #Date: Wed, 21 May 1997 01:17:59 GMT
                #Server: NCSA/1.4
                #Location: http://HTTP.CS.Berkeley.EDU/~kchang/
                #Content-type: text/html
                # 
                #HTTP/1.0 404 Not Found
                #Date: Wed, 21 May 1997 01:20:18 GMT
                #Server: NCSA/1.4
                #Content-type: text/html
                #Last-modified: Mon, 12 May 1997 18:46:57 GMT
                #Content-length: 683

                if {[string first "HTTP/1.0" $line]} {
                    set status [lindex $line 1]
                }
                


            }
        } else {
            # Body mode
            ::puts $tmpfd $line
        }
    }
}

#########################################################################
#### httpwait
# Wait until the variable name has been changed.
body ::tycho::ResourceHTTP::httpwait {} {
    global $statusVariableName
    ::puts "status: $statusVariableName"
    if {[uplevel #0 "set $statusVariableName"]=="running"} {
        tkwait variable $statusVariableName
    }
    return [uplevel #0 "set $statusVariableName"]
}


    ###################################################################
    ####                        public procs                       ####

#########################################################################
#### httpsetstatus
# Helper function to set the global variable
# This is used so that tkwait can wait for
# the global variable to change from "running" to either
# "normal" or "abnormal"

proc httpStatus {name value} {
    global $name
    set $name $value
}
