# Makefile for cgc/targets
# Copyright (c) 1996 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# @(#)makefile	1.7 8/18/96
#
# Important!  Do not run this makefile while in 
# $PTOLEMY/src/domains/cgc/targets.
# Instead run in from $PTOLEMY/obj.$PTARCH/domains/cgc/targets
# (through the symbolic link) --
# that way a separate directory containing, say, Sun-3 and Sun-4
# objects can be maintained.

include ../../../../mk/subdomain.mk

DIRS = uniproc multiproc NOWam

ME = cgc/targets

