##########################################################################
# Version: $Id$
# Author: John Reekie
#
# @Copyright (c) 1996-%Q% The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
##########################################################################


##########################################################################
#### ViewController
#
# _ViewController_ is the abstract superclass of controller objects
# for subclasses of _SlateView_. Not all subclasses will necessarily
# use ViewControllers, and some may choose to use several.
#
class ::tycho::ViewController {
	
    constructor {args} {}
    destructor {}
    
    #################################################################
    ####                        options                          ####

    # The semantic model
    public variable graph

    # The layout model
    public variable layout

    # The slate I control
    public variable slate
	
    # The slateview I am a controller of
    public variable slateview

    #################################################################
    ####                     public methods                      ####
    
    # Initialize the context-sensitive popup menu
    method contextmenu {item args}

    # Get or change the name of an item given its slate id
    method itemname {slateid {newname {}}}

    # Get the slate id of an item given its name
    method slateid {name}
}

########################################################################
#### constructor
#
body ::tycho::ViewController::constructor {args} {
    # Evaluate options
    eval configure $args
}

#########################################################################
#### contextmenu
#
# Initialize the context-sensitive pop-up menu. This default
# method does nothing. Subclasses should override to add
# additional items to the menu according to the passed
# item id
#
body ::tycho::ViewController::contextmenu {slateid args} {
    ;
}

#########################################################################
#### itemname
#
# Get the name of an item from its slate id.
#
body ::tycho::ViewController::itemname {slateid {newname {}}} {
	$slateview itemname $slateid $newname
}

#########################################################################
#### slateid
#
# Get the slateid of an item from its name.
#
body ::tycho::ViewController::slateid {name} {
	$slateview slateid $name
}
