# Makefile for sdf/matrix
# Copyright (c) 1990-1993 The Regents of the University of California.
#                         All Rights Reserved.
#		       
# $Id$
#
# Important!  Do not run this makefile while in 
# ~ptolemy/src/domains/sdf/matrix.  Instead run it from 
# ~ptolemy/obj.$ARCH/domains/sdf/matrix (through the symbolic
# link) -- that way a separate directory containing, say, Sun-3 and Sun-4
# objects can be maintained.

include ../../../../subdomain.mk

DIRS = stars

ME = sdf/matrix

