# Definition of an HTML context-sensitive editor.
#
# Author: Edward A. Lee
#
# Version: $Id$
#
# Copyright (c) 1990-%Q% The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
#######################################################################

#######################################################################
#### EditHTML
# This class defines a window containing an EditHTMLText widget, which
# provides an emacs-like editor specialized for editing HTML files.
#
class ::tycho::EditHTML {
    inherit ::tycho::Edit

    #### evaluate
    # Evaluate the HTML.
    method evaluate {}

    #### help
    # Open a help window.
    method help {}

    #### reload
    # Override the base-class reload to recolorize.
    method reload {}

    constructor {args} {}
    destructor {}

    #########################################################################
    #### protected methods

    #### textWidget
    # Return the name of the type of text widget to use.
    method textWidget {} {return ::tycho::EditHTMLText}
}

###################################################################
#
body ::tycho::EditHTML::constructor {args} {
    
    eval itk_initialize $args

    # Add to the format menu commands to comment and uncomment
    # the regions defined by the selection.
    $itk_component(formatMenu) add separator
        
    $itk_component(formatMenu) add command \
	    -label "Recolorize" \
	    -underline 0 \
	    -command [code $itk_component(text) parse]

    $itk_component(editMenu) add separator
        
    $itk_component(editMenu) add command \
	    -label "Check Links" \
	    -underline 6 \
	    -command [code $itk_component(text) checkLinks]

    # Read contents from the specified file, unless the name is "NoName".
    # This needs to be repeated from the baseclass because the -file
    # option will not have been processed by the time the base class
    # constructor is executed.
    if {$file != {NoName}} {
	$itk_component(text) initFile $file
	markUnmodified
    }
}

#####################################################################
#### evaluate
# Evaluate the contents of the text window as HTML commands.
#
body ::tycho::EditHTML::evaluate {} {
    $itk_component(text) evaluate
}

###################################################################
#### help
# Open a window with help on the current widget.
#
body ::tycho::EditHTML::help {} {
    global TYCHO
    ::tycho::File::openContext \
	    $TYCHO/editors/textedit/doc/usersGuides/EditHTMLHelp.html
}

#####################################################################
#### reload
# Override the base-class reload to recolorize.
#
body ::tycho::EditHTML::reload {} {
    Edit::reload 
    $itk_component(text) parse
}
