#! /bin/csh

# $Id$
#
# Copyright (c) %Q% The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY 
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES 
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF 
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF 
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# Programmer: Christopher Hylands

# This script sets things up to use a ptcl from a possibly older Ptolemy
# Usage: makeoldptcl oldptolemypath makeargs 
# For example: $PTOLEMY/src/tst/sbin/makeoldptcl /usr/eesww/share/ptolemy test

set OLDPTOLEMY=$1
shift

# Setup to use the OLDPTOLEMY g++ so that we properly compile the stars
source $OLDPTOLEMY/bin/g++-setup

# Be sure to place $PTOLEMY/src/tst/sbin in the path first so we get
# the testbed pxgraph
set path = ($PTOLEMY/src/tst/sbin $OLDPTOLEMY/bin.$PTARCH $path)

make PTOLEMY=$OLDPTOLEMY PTCL=$PTOLEMY/src/tst/sbin/ptcltst OCT2PTCL=$PTOLEMY/bin.$PTARCH/oct2ptcl TST_SBINDIR=$PTOLEMY/src/tst/sbin $*
