# Makefile for sdf/contrib, which contains user contributed stars
# Copyright (c) 1994 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# $Id$
#
# Important!  Do not run this makefile while in 
# ~ptolemy/src/domains/sdf/contrib.  Instead run in from
# ~ptolemy/obj.$ARCH/domains/sdf/contrib (through the symbolic
# link) -- that way a separate directory containing, say, Sun-3 and Sun-4
# objects can be maintained.

include ../../../../mk/subdomain.mk

DIRS = stars

ME = sdf/contrib

