.\" $Id$
.NA gaussian
.SD
Generate a Gaussian white noise signal, and plot its
histogram and estimated autocorrelation.
.DE
.LO "$PTOLEMY/src/domains/sdf/demo"
.DM SDF Universe
.SV $Revision$	$Date$
.AL "Edward A. Lee"
.LD
This system plots a histogram and estimated autocorrelation
of samples generated by an
.c IIDGaussian
star.
Note that since the
.c Autocor
star does block processing, this demo should be run for one iteration.
The number of Gaussian samples processed will be determined
by the \fInoInputsToAvg\fR parameter of the autocorrelation block.
.Se Xhistogram
.Se "IIDGaussian"
.Se "Autocor"
.Ie "Gaussian noise"
.Ie "noise, Gaussian"
.SA
Autocor,
IIDGaussian,
Xhistogram.
.ES
