# Makefile for sdf/dsp
# Copyright (c) 1990-1996 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# @(#)makefile	1.1 6/26/96
# 
# Important!  Do not run this makefile while in
# ~ptolemy/src/domains/cgc/dsp.  Instead run in from
# ~ptolemy/obj.$PTARCH/domains/cgc/dsp (through the symbolic link) --
# that way a separate directory containing, say, Sun-3 and Sun-4
# objects can be maintained.

include ../../../../mk/subdomain.mk

DIRS = stars

ME = cgc/dsp

