# Makefile for domains/sdf/image
# Copyright (c) 1990-1999 The Regents of the University of California.
#                       All Rights Reserved.
#		       
# @(#)makefile	1.4 01/31/96
#
# Important!  Do not run this makefile while in ~ptolemy/src/domains/sdf/image
# Instead run in from ~ptolemy/obj.$PTARCH/domains/sdf/image
# (through the symbolic link) -- that way a separate directory containing,
# say, Sun-3 and Sun-4 objects can be maintained.

include ../../../../mk/subdomain.mk

DIRS = stars

ME = sdf/image

