.\" $Id$
.TH play 1 "20 November 1989"
.SH NAME
play - play a sound file on the speaker
.SH SYNOPSIS
play [-l] [<file>]
.SH DESCRIPTION
Plays the specified file, or stdin.
The -l flag means loop - it plays the file repeatedly until interrupted.
.SH ENVIRONMENT
.nf
SST_PLAY - playback gain, from 0 to 99, default 75
SST_EARPHONES - if set, send output to the earphone jack
.fi
.SH "SEE ALSO"
record(1)
.SH AUTHOR
Copyright (C) 1989 by Jef Poskanzer.

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted, provided
that the above copyright notice appear in all copies and that both that
copyright notice and this permission notice appear in supporting
documentation.  This software is provided "as is" without express or
implied warranty.
