.\" $Id$
.TH ulawtolin 1 "20 November 1989"
.SH NAME
ulawtolin - convert a ulaw sound file to linear
.SH SYNOPSIS
ulawtolin [<file>]
.SH DESCRIPTION
Converts a ulaw sound file into linear, printable form - ASCII numbers
between -32768 and 32767.
.SH "SEE ALSO"
lintoulaw(1)
.SH AUTHOR
Copyright (C) 1989 by Jef Poskanzer.

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted, provided
that the above copyright notice appear in all copies and that both that
copyright notice and this permission notice appear in supporting
documentation.  This software is provided "as is" without express or
implied warranty.
