/* This file contains a table of the official VHDL stars.  Its purpose is
 * to force the linker to retrieve the corresponding stars from their
 * library.
 *
 * DO NOT EDIT THIS FILE!  It is generated automatically from the
 * make.template file's definition of PL_SRCS.
 */

#define STR extern char *

 STR star_nm_VHDLQuant;
 STR star_nm_VHDLAdd;
 STR star_nm_VHDLAddCx;
 STR star_nm_VHDLAddInt;
 STR star_nm_VHDLAverage;
 STR star_nm_VHDLBlackHole;
 STR star_nm_VHDLConst;
 STR star_nm_VHDLConstCx;
 STR star_nm_VHDLConstInt;
 STR star_nm_VHDLCos;
 STR star_nm_VHDLCxToFloat;
 STR star_nm_VHDLCxToRect;
 STR star_nm_VHDLDistributor;
 STR star_nm_VHDLDownSample;
 STR star_nm_VHDLExp;
 STR star_nm_VHDLFIR;
 STR star_nm_VHDLFIRInt;
 STR star_nm_VHDLFloatToCx;
 STR star_nm_VHDLFork;
 STR star_nm_VHDLGain;
 STR star_nm_VHDLGainInt;
 STR star_nm_VHDLImpulse;
 STR star_nm_VHDLInhomogeneous;
 STR star_nm_VHDLIntegrator;
 STR star_nm_VHDLLMS;
 STR star_nm_VHDLMpy;
 STR star_nm_VHDLMpyCx;
 STR star_nm_VHDLMpyInt;
 STR star_nm_VHDLPolarToRect;
 STR star_nm_VHDLRamp;
 STR star_nm_VHDLRampInt;
 STR star_nm_VHDLRect;
 STR star_nm_VHDLRectToCx;
 STR star_nm_VHDLRectToPolar;
 STR star_nm_VHDLSin;
 STR star_nm_VHDLSub;
 STR star_nm_VHDLSubInt;
 STR star_nm_VHDLUpSample;
 STR star_nm_VHDLWaveForm;
 STR star_nm_VHDLWaveFormCx;
 STR star_nm_VHDLWindow;
 STR star_nm_VHDLXgraph;
 STR star_nm_VHDLXMgraph;
 STR star_nm_VHDLXYgraph;
static char** nm_table[] = {
 &star_nm_VHDLQuant,
 &star_nm_VHDLAdd,
 &star_nm_VHDLAddCx,
 &star_nm_VHDLAddInt,
 &star_nm_VHDLAverage,
 &star_nm_VHDLBlackHole,
 &star_nm_VHDLConst,
 &star_nm_VHDLConstCx,
 &star_nm_VHDLConstInt,
 &star_nm_VHDLCos,
 &star_nm_VHDLCxToFloat,
 &star_nm_VHDLCxToRect,
 &star_nm_VHDLDistributor,
 &star_nm_VHDLDownSample,
 &star_nm_VHDLExp,
 &star_nm_VHDLFIR,
 &star_nm_VHDLFIRInt,
 &star_nm_VHDLFloatToCx,
 &star_nm_VHDLFork,
 &star_nm_VHDLGain,
 &star_nm_VHDLGainInt,
 &star_nm_VHDLImpulse,
 &star_nm_VHDLInhomogeneous,
 &star_nm_VHDLIntegrator,
 &star_nm_VHDLLMS,
 &star_nm_VHDLMpy,
 &star_nm_VHDLMpyCx,
 &star_nm_VHDLMpyInt,
 &star_nm_VHDLPolarToRect,
 &star_nm_VHDLRamp,
 &star_nm_VHDLRampInt,
 &star_nm_VHDLRect,
 &star_nm_VHDLRectToCx,
 &star_nm_VHDLRectToPolar,
 &star_nm_VHDLSin,
 &star_nm_VHDLSub,
 &star_nm_VHDLSubInt,
 &star_nm_VHDLUpSample,
 &star_nm_VHDLWaveForm,
 &star_nm_VHDLWaveFormCx,
 &star_nm_VHDLWindow,
 &star_nm_VHDLXgraph,
 &star_nm_VHDLXMgraph,
 &star_nm_VHDLXYgraph,
};
