#!/bin/sh
# $Id$
#
# Copyright (c) %Q% The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY 
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES 
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF 
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF 
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# Programmer: Christopher Hylands

# Diff two directories, if any of the files are different and are of
# the form *.pt.*, then run epsilondiff

if [ $# -ne 3 -o ! -d $2 -o ! -d $3 ]; then
	echo "Usage: tstdiff -r directory1 directory2"
	exit 3
fi
shift

tmpls1=/tmp/tstdiff1.$$
tmpls2=/tmp/tstdiff2.$$

ls $1 | sort > $tmpls1
ls $2 | sort > $tmpls2

comm -23 $tmpls1 $tmpls2 | awk '{print "Only in", dir ":", $0}' dir=$1

comm -13 $tmpls1 $tmpls2 | awk '{print "Only in", dir ":", $0}' dir=$2

for file in `cat $tmpls1`
do
	if [ -f $1/$file -a -f $2/$file ]; then
		diff $1/$file $2/$file > /dev/null 2>&1
		status=$?
		if [ $status -eq 1 ]; then
			echo "diff -r $1/$file $2/$file"
			diff $1/$file $2/$file
			echo $file | egrep -s '.*\.pt\..*'
			status=$?	
			if [ $status = 0 ]; then
				#echo "Binary files $1/$file and $2/$file differ"
				wc $1/$file $2/$file
				$PTOLEMY/src/tst/sbin/epsilondiff $1/$file $2/$file
			fi
		fi
	fi
done

rm -f $tmpls1 $tmpls2
