# Test suite for Loader that will work from within itclsh
#
# @Authors: Christopher Hylands
#
# @Version: $Id$
#
# @Copyright (c) 1996-%Q% The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
#######################################################################

# @(#)testGraph.itcl	1.4  13 Oct 1996

if {[string compare test [info procs test]] == 1} then { 
    source [file join $TYCHO kernel test testDefs.tcl]
    source testDefs.tcl
} {}

# If necessary load up the definition
if {[namespace tycho {info proc loadIfNotPresent}] == {} } {
    namespace tycho
    source ../Loader.tcl
}

test Loader-1.1 {load up the profile command} {
    if ![info exists env(PTARCH)] {
	error "env(PTARCH) does not exist, perhaps the PTARCH environment\
		variable is not set?"
    }
    set profileobjdir [file join $TYCHO obj.$env(PTARCH) profile]
    set profileobj [file join $profileobjdir \
	    tclXprofile[info sharedlibextension]]
    file delete -force $profileobjdir
    if ![file exists $profileobj] {
	puts "About to run make tclexts"
	::tycho::execModal {make tclexts} $TYCHO
    }
    ::tycho::loadIfNotPresent profile tclx [list \
	    [list tclXprofile $profileobjdir]]
} {}

