# Makefile for de/tcltk
# Copyright (c) 1993-%Q% The Regents of the University of California.
#                       All Rights Reserved.
#		       
# $Id$
#
# Important!  Do not run this makefile while in ~ptolemy/src/domains/de/tcltk.
# Instead run in from ~ptolemy/obj.$PTARCH/domains/de/tcltk (through the
# symbolic link) -- that way a separate directory containing, say,
# Sun-3 and Sun-4 objects can be maintained.

include ../../../../mk/subdomain.mk

DIRS = stars

ME = de/tcltk

