# sets the default Options for widgets and windows used by Pigi
#
# Author: Alan Kamas and Kennard White
# Version: $Id$
#
# Copyright (c) 1990-1993 The Regents of the University of California.
# All rights reserved.
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
#
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#                                                         COPYRIGHTENDKEY

# All font values should be set here.  This will allow users with
# limited fonts to adjust them here, in one place rather than throughout
# the code.

# Set up defaults for the PigiWindows:
# ###################################

# Define font types used in PigiWindows:
option add Pigi.mainfont -Adobe-times-medium-r-normal--*-180*
option add Pigi.bigfont  -Adobe-Helvetica-Bold-R-Normal-*-240-*

# set font for all message windows used in Pigi
option add *Pigi*Message*Font [option get . mainfont Mainfont]
option add *Pigi*Scale*Foreground [ptkColor bisque1]
option add *Pigi*Scale*SliderForeground [ptkColor bisque1]
option add *Pigi*Scale*Background [ptkColor tan4]



# Set up defaults for the Windows generated by CGC programs
# #########################################################
option add CGC.mainfont -Adobe-times-medium-r-normal--*-180*
option add CGC.bigfont  -Adobe-Helvetica-Bold-R-Normal-*-240-*
option add *CGC*Message*Font [option get . mainfont Mainfont]
# set the specific interations entry window color
option add CGC.numberIters.entry.background [ptkColor wheat3]
# set general options for all CGC windows
option add *CGC*Button*Foreground [ptkColor blue3]
option add *CGC*Scale*Foreground [ptkColor bisque1]
option add *CGC*Scale*SliderForeground [ptkColor bisque1]
option add *CGC*Scale*Background [ptkColor tan4]
option add *CGC*Entry*Background [ptkColor burlywood1]

