# Test suite for commands that run applications in pitcl.
#
# @Author: Edward A. Lee
#
# @Version: $Id$
#
# @Copyright (c) 1997 The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
#######################################################################

if {[string compare test [info procs test]] == 1} then { 
    source $TYCHO/kernel/test/testDefs.tcl
} {}

# Uncomment this to get a full report, or set in your Tcl shell window.
# set VERBOSE 1

# Set the following to avoid endless calls to exit.
set reallyExit 0

######################################################################
#### setup
# Create a simple universe.

test run-0 {create a test universe} {
    namespace ::pitcl {
        addUniverse x SDF
        addBlock a WaveForm
        addBlock b Ramp
        addBlock c Add
        # FIXME: Make this a non-graphical test
        addBlock d Xgraph
        connect .x.a.output .x.c.input
        connect .x.b.output .x.c.input
        connect .x.c.output .x.d.input
    }
} {}

######################################################################
#### run

test run-1 {Check getDomain on the universe} {
    ::pitcl::run .x 10
    ::pitcl::wrapup
} {}

# FIXME: wormhole test.
test run-0 {create a test universe} {
    namespace ::pitcl {
        defWormhole ymw SDF DE {} {
            addBlock z BlackHole
            galaxyPort in z.input
        }
        defWormhole zmw SDF SDF {loop-SDF} {
            addBlock e Ramp
            galaxyPort out e.output
        }
        addUniverse y SDF
        addBlock y ymw
        addBlock b Const
        addBlock c Add
        addBlock z zmw
        connect .y.z.out .y.c.input
        connect .y.b.output .y.c.input
        connect .y.c.output .y.y.in
    }
} {}



doneTests
