# Test the Rectangle shape
#
# @Author: John Reekie
# 
# @Version: @(#)testRectangle.itcl	1.6 07/29/98
#
# @Copyright (c) 1997-1998 The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
#######################################################################

# Make sure that the test package is loaded
package require slate.test


#######################################################################
#### _feature

#######################################################################
#### _grapple

#######################################################################
#### _reshape

#######################################################################
#### _reshapeclick
#### _reshapedrag
#### _reshaperelease
#
# These methods are tested as a set.
#
# FIXME: What about multiple features specified?
#
set delta 30
set i 0

foreach a {n s e w ne nw se sw} {
    incr i
    _twoitems
   test Rectangle-_reshapeclick.$i \
            "Reshape a simple item, no ghosting, $a" {
        _interact ::tycho::Rectangle::_reshape $r 1 1 $delta -features $a
    } [_finally ::tycho::Rectangle::reshape $r 1 1 $delta $a]
}

foreach a {n s e w ne nw se sw} {
    incr i
    _twoitems
   test Rectangle-_reshapeclick.$i \
            "Reshape a simple item, with ghosting, $a" {
        _interact ::tycho::Rectangle::_reshape $r 1 1 $delta \
                -features $a -ghost 1
    } [_finally ::tycho::Rectangle::reshape $r 1 1 $delta $a]
}

foreach a {n s e w ne nw se sw} {
    incr i
    _twoitems
   test Rectangle-_reshapeclick.$i \
            "Reshape a complex item by tag, no ghosting, $a" {
        _interact ::tycho::Rectangle::_reshape $f -1 -1 $delta \
                -features $a
    } [_finally ::tycho::Rectangle::reshape $f -1 -1 $delta $a]
}


##########################################################################
#### feature

##########################################################################
#### inside

##########################################################################
#### overlap

#######################################################################
#### reshape

#######################################################################
#### shrink

#######################################################################
#### stretch

##########################################################################
#### union

