# Test the IconFrame item
#
# @Author: John Reekie
# 
# @Version: $Id$
#
# @Copyright (c) 1997 The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
#######################################################################

if {[string compare test [info procs test]] == 1} then { 
    source [file join $TYCHO kernel test testDefs.tcl]
} {}

if {[string compare test [info procs _slate]] == 1} then { 
    source [file join $TYCHO editors slate test defs.itcl]
} {}

if { ! [::info exists SHORTTIME] } {
    set SHORTTIME 100
}
#set VERBOSE 1

############################################################################
#### Define a proc that creates a single IconFrame on the slate
#
proc _frame {args} {
    global f
    _clean
    set f [.s create IconFrame 100 100 \
	    -color green -tags foo \
	    -text Hello \
	    -hsize 60 -vsize 40 \
	    -graphics {Frame 10 10 50 50 -color green -relief sunken;
                Frame 50 50 90 90 -color blue}]
    eval .s itemconfigure $f $args
}

############################################################################
#### Define another proc that creates a single IconFrame on the slate
#
proc _emptyframe {args} {
    global f
    _clean
    set f [.s create IconFrame 100 100 \
	    -color green -tags foo \
	    -hsize 60 -vsize 40 \
	    -text Hello]
    eval .s itemconfigure $f $args
}

#######################################################################
#### Creation
#
_slate
test IconFrame-construct-1 {Create a IconFrame item and check coords} {
    _frame
    .s coords [.s primary $f]
} {70.0 80.0 130.0 120.0}

#######################################################################
#### Options
#
_slate
set i 0

### Defaults

set f [.s create IconFrame 40 40 80 80]
update
foreach {opt val} {\
        -relief raised \
        -color background \
        -shape point \
        -borderwidth 2 \
        -tags {} \
        -text NoName \
        -textanchor center \
        -graphics {} \
        -hsize 60 \
        -vsize 40 \
        -anchor center } {
    incr i
    test IconFrame-options-$i "Check default option $opt" {
        .s itemcget $f $opt
    } $val
}
update
after $SHORTTIME

_clean
set f [.s create IconFrame 140 140 180 180 \
        -relief sunken \
        -color green \
        -borderwidth 4 \
        -tags foo \
        -text Foo \
        -textanchor s \
        -graphics {line 0 0 100 100} \
        -hsize 80 \
        -vsize 20 \
        -anchor nw]
update
foreach {opt val} {\
        -relief sunken \
        -color green \
        -borderwidth 4 \
        -tags foo \
        -text Foo \
        -textanchor s \
        -graphics {line 0 0 100 100} \
         -hsize 80 \
        -vsize 20 \
        -anchor nw } {
    incr i
    test IconFrame-options-$i "Check non-default option $opt" {
        .s itemcget $f $opt
    } $val
}
update
after $SHORTTIME

#### -relief

_frame
set i 0
foreach r {flat raised sunken} \
	c {{green3 green3 green3} {green1 green3 green4} \
	{green4 green3 green1}} {
    incr i
    test IconFrame-relief-$i "Check coloring for relief $r" {
	.s itemconfigure $f -relief $r
	list \
		[.s component $f lit itemcget -fill] \
		[.s component $f surface itemcget -fill] \
		[.s component $f shaded itemcget -fill]
    } $c
    update idletasks
    after $SHORTTIME
}
    
_frame
foreach r {ridge groove} \
	c {{green1 green3 green4 green4 green1} \
	{green4 green3 green1 green1 green4}} {
    incr i
    test IconFrame-relief-$i "Check coloring for relief $r" {
	.s itemconfigure $f -relief $r
	list \
		[.s component $f lit itemcget -fill] \
		[.s component $f surface itemcget -fill] \
		[.s component $f shaded itemcget -fill] \
		[.s component $f notlit itemcget -fill] \
		[.s component $f notshaded itemcget -fill]
    } $c
    update idletasks
    after $SHORTTIME
}

#### -borderwidth
    
_frame
set i 0
foreach b {0 1 2} \
	c {{70.0 80.0 131.0 121.0} {71.0 81.0 130.0 120.0} {72.0 82.0 129.0 119.0}} {
    incr i
    test IconFrame-borderwidth-$i "Check border width $b" {
	.s itemconfigure $f -borderwidth $b
	.s component $f surface coords
    } $c
    update idletasks
    after $SHORTTIME
}
    
#### -color
    
_frame
set i 0
foreach c {red blue yellow} {
    incr i
    test IconFrame-color-$i "Check coloring change to $c" {
	.s itemconfigure $f -color $c
	.s component $f surface itemcget -fill
    } ${c}3
    update idletasks
    after $SHORTTIME
}

#### -anchor
    
_frame -text Bar
set i 0
foreach a {n s e w nw sw ne se c} p {s n w e sw nw se ne n} {
    incr i
    test IconFrame-anchor-$i "Check anchoring, graphics, $a" {
        .s itemconfigure $f -textanchor $a
        .s component $f label itemcget -anchor
    } $p
    update
    after $SHORTTIME
}

#### -hsize

_frame
test IconFrame-hsize-1 {Test -hsize} {
    .s itemconfigure $f -hsize 100
    .s coords [.s primary $f]
} {50.0 80.0 150.0 120.0}
update
after $SHORTTIME

test IconFrame-hsize-2 {Test invalid -hsize} {
    catch {.s itemconfigure $f -hsize 0} msg
    set msg
} {Invalid -hsize: 0}

#### -vsize

_frame
test IconFrame-vsize-1 {Test -vsize} {
    .s itemconfigure $f -vsize 100
    .s coords [.s primary $f]
} {70.0 50.0 130.0 150.0}
update
after $SHORTTIME

test IconFrame-vsize-2 {Test invalid -vsize} {
    catch {.s itemconfigure $f -vsize 0} msg
    set msg
} {Invalid -vsize: 0}


#######################################################################
#### Terminals
#
_frame
test IconFrame-terminal-1 "Create a terminal and access as component" {
    .s call $f terminal input-1 Terminal 0 0 \
            -anchor {50 0} \
            -direction {0 -1} \
            -length 20 \
            -type input \
            -style doublearrow
    # Test: just make sure we get something
    expr { [.s component $f input-1] != "" }
} {1}
update
after $SHORTTIME
after $SHORTTIME

test IconFrame-terminal-2 "Create a terminal and get coordinates" {
    .s call $f terminal input-2 Terminal 0 0 \
            -anchor {0 50} \
            -direction {-1 0} \
            -length 30 \
            -type input \
            -style blob -fill blue
    # Test: get the two ends of both terminals
    list \
            [.s aspect [.s component $f input-1] origin terminal] \
            [.s aspect [.s component $f input-2] origin terminal]
} {{100.0 80.0 100.0 60.0} {70.0 100.0 40.0 100.0}}
update
after $SHORTTIME

test IconFrame-terminal-3 "Resize and check terminals have moves" {
    .s itemconfigure $f -hsize 100 -vsize 100
   # Test: get the two ends of both terminals
    list \
            [.s aspect [.s component $f input-1] origin terminal] \
            [.s aspect [.s component $f input-2] origin terminal]
} {{100.0 50.0 100.0 30.0} {50.0 100.0 20.0 100.0}}
update
after $SHORTTIME


