# Test ICanvas methods
#
# @Author: John Reekie
# 
# @Version: $Id$
#
# @Copyright (c) 1997 The Regents of the University of California.
# All rights reserved.
# 
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# 
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY
#######################################################################

if {[string compare test [info procs test]] == 1} then { 
    source [file join $TYCHO kernel test testDefs.tcl]
} {}
# See tycho/editors/slate/doc/internals/tute-drawing.html

## These tests test out only the methods in ICanvas. For tests
# that apply to individual item types, shapes, or interactors,
# see the individual test files. For test of the methods
# in Slate.itcl, see testSlate.itcl.

############################################################################
#### Construction tests
#
test IncrCanvas-1.1 {Simplest construction test} {
   catch {delete object .c}
   ::tycho::icanvas .c
} {.c}

# FIXME: add more tests with different options

############################################################################
#### Simple item creation
#
catch {delete object .c}
::tycho::icanvas .c

update
test IncrCanvas-2.1 {Create simple canvas items} {
    set result {}
    # FIXME: Add other item types
    foreach item {
	{rectangle 100 100 200 200 -fill blue}
	{oval 100 100 200 200 -outline green}
	{line 100 100 200 200 -arrow last}
    } {
	set i [eval .c create $item]
	lappend result [expr $i-$i]
	.c delete $i
    }
} {0 0 0}

	
